// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A generic account that represents any party's account at another party. Parties may be identified by the account at another party.
 */
public class Account implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private PartyReference accountBeneficiary;
	
	@Attribute  
	private String id;
	
    
	/**
     * public getter
     *
     * A reference to the party beneficiary of the account.
     *
     * @returns com.leansoft.fpml.nano.PartyReference
	 */
	public PartyReference getAccountBeneficiary() {
	    return this.accountBeneficiary;
	}
	
	/**
	 * public setter
	 *
     * A reference to the party beneficiary of the account.
     *
     * @param com.leansoft.fpml.nano.PartyReference
	 */
	public void setAccountBeneficiary(PartyReference accountBeneficiary) {
	    this.accountBeneficiary = accountBeneficiary;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}