// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Specifies the amount of the fee along with, when applicable, the formula that supports its determination.
 */
public class AdditionalPaymentAmount implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Money paymentAmount;
	
	@Element
	private Formula formula;
	
    
	/**
     * public getter
     *
     * The currency amount of the payment.
     *
     * @returns com.leansoft.fpml.nano.Money
	 */
	public Money getPaymentAmount() {
	    return this.paymentAmount;
	}
	
	/**
	 * public setter
	 *
     * The currency amount of the payment.
     *
     * @param com.leansoft.fpml.nano.Money
	 */
	public void setPaymentAmount(Money paymentAmount) {
	    this.paymentAmount = paymentAmount;
	}
	/**
     * public getter
     *
     * Specifies a formula, with its description and components.
     *
     * @returns com.leansoft.fpml.nano.Formula
	 */
	public Formula getFormula() {
	    return this.formula;
	}
	
	/**
	 * public setter
	 *
     * Specifies a formula, with its description and components.
     *
     * @param com.leansoft.fpml.nano.Formula
	 */
	public void setFormula(Formula formula) {
	    this.formula = formula;
	}

}