// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

public class AdjustableRelativeOrPeriodicDates implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private AdjustableDates adjustableDates;
	
	@Element
	private RelativeDateSequence relativeDateSequence;
	
	@Element
	private PeriodicDates periodicDates;
	
	@Attribute  
	private String id;
	
    
	/**
     * public getter
     *
     * A series of dates that shall be subject to adjustment if they would otherwise fall on a day that is not a business day in the specified business centers, together with the convention for adjusting the date.
     *
     * @returns com.leansoft.fpml.nano.AdjustableDates
	 */
	public AdjustableDates getAdjustableDates() {
	    return this.adjustableDates;
	}
	
	/**
	 * public setter
	 *
     * A series of dates that shall be subject to adjustment if they would otherwise fall on a day that is not a business day in the specified business centers, together with the convention for adjusting the date.
     *
     * @param com.leansoft.fpml.nano.AdjustableDates
	 */
	public void setAdjustableDates(AdjustableDates adjustableDates) {
	    this.adjustableDates = adjustableDates;
	}
	/**
     * public getter
     *
     * A series of dates specified as some offset to other dates (the anchor dates) which can
     *
     * @returns com.leansoft.fpml.nano.RelativeDateSequence
	 */
	public RelativeDateSequence getRelativeDateSequence() {
	    return this.relativeDateSequence;
	}
	
	/**
	 * public setter
	 *
     * A series of dates specified as some offset to other dates (the anchor dates) which can
     *
     * @param com.leansoft.fpml.nano.RelativeDateSequence
	 */
	public void setRelativeDateSequence(RelativeDateSequence relativeDateSequence) {
	    this.relativeDateSequence = relativeDateSequence;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.PeriodicDates
	 */
	public PeriodicDates getPeriodicDates() {
	    return this.periodicDates;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.PeriodicDates
	 */
	public void setPeriodicDates(PeriodicDates periodicDates) {
	    this.periodicDates = periodicDates;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}