// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type defining a date (referred to as the derived date) as a relative offset from another date (referred to as the anchor date) plus optional date adjustments.
 */
public class AdjustedRelativeDateOffset extends RelativeDateOffset implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private BusinessDayAdjustments relativeDateAdjustments;
	
    
	/**
     * public getter
     *
     * The business day convention and financial business centers used for adjusting the relative date if it would otherwise fall on a day that is not a business date in the specified business centers.
     *
     * @returns com.leansoft.fpml.nano.BusinessDayAdjustments
	 */
	public BusinessDayAdjustments getRelativeDateAdjustments() {
	    return this.relativeDateAdjustments;
	}
	
	/**
	 * public setter
	 *
     * The business day convention and financial business centers used for adjusting the relative date if it would otherwise fall on a day that is not a business date in the specified business centers.
     *
     * @param com.leansoft.fpml.nano.BusinessDayAdjustments
	 */
	public void setRelativeDateAdjustments(BusinessDayAdjustments relativeDateAdjustments) {
	    this.relativeDateAdjustments = relativeDateAdjustments;
	}

}