// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type for defining a series of dates, either as a list of adjustable dates, or a as a repeating sequence from a base date
 */
public class AdjustableDatesOrRelativeDateOffset implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private AdjustableDates adjustableDates;
	
	@Element
	private RelativeDateOffset relativeDate;
	
    
	/**
     * public getter
     *
     * A series of adjustable dates
     *
     * @returns com.leansoft.fpml.nano.AdjustableDates
	 */
	public AdjustableDates getAdjustableDates() {
	    return this.adjustableDates;
	}
	
	/**
	 * public setter
	 *
     * A series of adjustable dates
     *
     * @param com.leansoft.fpml.nano.AdjustableDates
	 */
	public void setAdjustableDates(AdjustableDates adjustableDates) {
	    this.adjustableDates = adjustableDates;
	}
	/**
     * public getter
     *
     * A series of dates specified as a repeating sequence from a base date
     *
     * @returns com.leansoft.fpml.nano.RelativeDateOffset
	 */
	public RelativeDateOffset getRelativeDate() {
	    return this.relativeDate;
	}
	
	/**
	 * public setter
	 *
     * A series of dates specified as a repeating sequence from a base date
     *
     * @param com.leansoft.fpml.nano.RelativeDateOffset
	 */
	public void setRelativeDate(RelativeDateOffset relativeDate) {
	    this.relativeDate = relativeDate;
	}

}