// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A notification to inform downstream systems when a system that acts as source of trade information detects that a new allocation has been created.
 */
@RootElement(name = "allocationCreated", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class AllocationCreated extends NotificationMessage implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<Trade> trade;
	
	@Element
	private List<Party> party;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Trade>
	 */
	public List<Trade> getTrade() {
	    return this.trade;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Trade>
	 */
	public void setTrade(List<Trade> trade) {
	    this.trade = trade;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}