// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A notification to inform downstream systems when a system that acts as source of trade information detects that an allocation has been cancelled.
 */
@RootElement(name = "allocationCancelled", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class AllocationCancelled extends NotificationMessage implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<Object> tradeOrPartyTradeIdentifier;
	
	@Element
	private List<Party> party;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<java.lang.Object>
	 */
	public List<Object> getTradeOrPartyTradeIdentifier() {
	    return this.tradeOrPartyTradeIdentifier;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<java.lang.Object>
	 */
	public void setTradeOrPartyTradeIdentifier(List<Object> tradeOrPartyTradeIdentifier) {
	    this.tradeOrPartyTradeIdentifier = tradeOrPartyTradeIdentifier;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}