// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A specific approval state in the workflow.
 */
public class Approval implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private String type;
	
	@Element
	private String status;
	
	@Element
	private String approver;
	
    
	/**
     * public getter
     *
     * The type of approval (e.g. "Credit").
     *
     * @returns java.lang.String
	 */
	public String getType() {
	    return this.type;
	}
	
	/**
	 * public setter
	 *
     * The type of approval (e.g. "Credit").
     *
     * @param java.lang.String
	 */
	public void setType(String type) {
	    this.type = type;
	}
	/**
     * public getter
     *
     * The current state of approval (.e.g preapproved, pending approval, etc.)
     *
     * @returns java.lang.String
	 */
	public String getStatus() {
	    return this.status;
	}
	
	/**
	 * public setter
	 *
     * The current state of approval (.e.g preapproved, pending approval, etc.)
     *
     * @param java.lang.String
	 */
	public void setStatus(String status) {
	    this.status = status;
	}
	/**
     * public getter
     *
     * The full name or identifiying ID of the relevant approver.
     *
     * @returns java.lang.String
	 */
	public String getApprover() {
	    return this.approver;
	}
	
	/**
	 * public setter
	 *
     * The full name or identifiying ID of the relevant approver.
     *
     * @param java.lang.String
	 */
	public void setApprover(String approver) {
	    this.approver = approver;
	}

}