// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * Period over which an average value is taken
 */
public class AveragingPeriod implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<AveragingSchedule> schedule;
	
	@Element
	private DateTimeList averagingDateTimes;
	
	@Element
	private MarketDisruption marketDisruption;
	
    
	/**
     * public getter
     *
     * A Equity Derivative schedule.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.AveragingSchedule>
	 */
	public List<AveragingSchedule> getSchedule() {
	    return this.schedule;
	}
	
	/**
	 * public setter
	 *
     * A Equity Derivative schedule.
     *
     * @param java.util.List<com.leansoft.fpml.nano.AveragingSchedule>
	 */
	public void setSchedule(List<AveragingSchedule> schedule) {
	    this.schedule = schedule;
	}
	/**
     * public getter
     *
     * Averaging DateTimes
     *
     * @returns com.leansoft.fpml.nano.DateTimeList
	 */
	public DateTimeList getAveragingDateTimes() {
	    return this.averagingDateTimes;
	}
	
	/**
	 * public setter
	 *
     * Averaging DateTimes
     *
     * @param com.leansoft.fpml.nano.DateTimeList
	 */
	public void setAveragingDateTimes(DateTimeList averagingDateTimes) {
	    this.averagingDateTimes = averagingDateTimes;
	}
	/**
     * public getter
     *
     * The market disruption event as defined by ISDA 2002 Definitions
     *
     * @returns com.leansoft.fpml.nano.MarketDisruption
	 */
	public MarketDisruption getMarketDisruption() {
	    return this.marketDisruption;
	}
	
	/**
	 * public setter
	 *
     * The market disruption event as defined by ISDA 2002 Definitions
     *
     * @param com.leansoft.fpml.nano.MarketDisruption
	 */
	public void setMarketDisruption(MarketDisruption marketDisruption) {
	    this.marketDisruption = marketDisruption;
	}

}