// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "bankruptcy", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class BankruptcyEvent extends CreditEvent implements Serializable {

    private static final long serialVersionUID = -1L;

    

}