// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A complex type to specify the strike of a bond or convertible bond option.
 */
public class BondOptionStrike implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private ReferenceSwapCurve referenceSwapCurve;
	
	@Element
	private OptionStrike price;
	
    
	/**
     * public getter
     *
     * The strike of an option when expressed by reference to a swap curve. (Typically the case for a convertible bond option.)
     *
     * @returns com.leansoft.fpml.nano.ReferenceSwapCurve
	 */
	public ReferenceSwapCurve getReferenceSwapCurve() {
	    return this.referenceSwapCurve;
	}
	
	/**
	 * public setter
	 *
     * The strike of an option when expressed by reference to a swap curve. (Typically the case for a convertible bond option.)
     *
     * @param com.leansoft.fpml.nano.ReferenceSwapCurve
	 */
	public void setReferenceSwapCurve(ReferenceSwapCurve referenceSwapCurve) {
	    this.referenceSwapCurve = referenceSwapCurve;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.OptionStrike
	 */
	public OptionStrike getPrice() {
	    return this.price;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.OptionStrike
	 */
	public void setPrice(OptionStrike price) {
	    this.price = price;
	}

}