// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Identifies the market sector in which the trade has been arranged.
 */
public class BrokerConfirmation implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private BrokerConfirmationType brokerConfirmationType;
	
    
	/**
     * public getter
     *
     * The type of broker confirmation executed between the parties.
     *
     * @returns com.leansoft.fpml.nano.BrokerConfirmationType
	 */
	public BrokerConfirmationType getBrokerConfirmationType() {
	    return this.brokerConfirmationType;
	}
	
	/**
	 * public setter
	 *
     * The type of broker confirmation executed between the parties.
     *
     * @param com.leansoft.fpml.nano.BrokerConfirmationType
	 */
	public void setBrokerConfirmationType(BrokerConfirmationType brokerConfirmationType) {
	    this.brokerConfirmationType = brokerConfirmationType;
	}

}