// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type defining a range of contiguous business days by defining an unadjusted first date, an unadjusted last date and a business day convention and business centers for adjusting the first and last dates if they would otherwise fall on a non business day in the specified business centers. The days between the first and last date must also be good business days in the specified centers to be counted in the range.
 */
public class BusinessDateRange extends DateRange implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private BusinessDayConventionEnum businessDayConvention;
	
	@Element
	private BusinessCentersReference businessCentersReference;
	
	@Element
	private BusinessCenters businessCenters;
	
    
	/**
     * public getter
     *
     * The convention for adjusting a date if it would otherwise fall on a day that is not a business day.
     *
     * @returns com.leansoft.fpml.nano.BusinessDayConventionEnum
	 */
	public BusinessDayConventionEnum getBusinessDayConvention() {
	    return this.businessDayConvention;
	}
	
	/**
	 * public setter
	 *
     * The convention for adjusting a date if it would otherwise fall on a day that is not a business day.
     *
     * @param com.leansoft.fpml.nano.BusinessDayConventionEnum
	 */
	public void setBusinessDayConvention(BusinessDayConventionEnum businessDayConvention) {
	    this.businessDayConvention = businessDayConvention;
	}
	/**
     * public getter
     *
     * A pointer style reference to a set of financial business centers defined elsewhere in the document. This set of business centers is used to determine whether a particular day is a business day or not.
     *
     * @returns com.leansoft.fpml.nano.BusinessCentersReference
	 */
	public BusinessCentersReference getBusinessCentersReference() {
	    return this.businessCentersReference;
	}
	
	/**
	 * public setter
	 *
     * A pointer style reference to a set of financial business centers defined elsewhere in the document. This set of business centers is used to determine whether a particular day is a business day or not.
     *
     * @param com.leansoft.fpml.nano.BusinessCentersReference
	 */
	public void setBusinessCentersReference(BusinessCentersReference businessCentersReference) {
	    this.businessCentersReference = businessCentersReference;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.BusinessCenters
	 */
	public BusinessCenters getBusinessCenters() {
	    return this.businessCenters;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.BusinessCenters
	 */
	public void setBusinessCenters(BusinessCenters businessCenters) {
	    this.businessCenters = businessCenters;
	}

}