// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * A type for defining a time with respect to a business center location. For example, 11:00am London time.
 */
public class BusinessCenterTime implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Date hourMinuteTime;
	
	@Element
	private BusinessCenter businessCenter;
	
    
	/**
     * public getter
     *
     * A time specified in hh:mm:ss format where the second component must be '00', e.g. 11am would be represented as 11:00:00.
     *
     * @returns java.util.Date
	 */
	public Date getHourMinuteTime() {
	    return this.hourMinuteTime;
	}
	
	/**
	 * public setter
	 *
     * A time specified in hh:mm:ss format where the second component must be '00', e.g. 11am would be represented as 11:00:00.
     *
     * @param java.util.Date
	 */
	public void setHourMinuteTime(Date hourMinuteTime) {
	    this.hourMinuteTime = hourMinuteTime;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.BusinessCenter
	 */
	public BusinessCenter getBusinessCenter() {
	    return this.businessCenter;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.BusinessCenter
	 */
	public void setBusinessCenter(BusinessCenter businessCenter) {
	    this.businessCenter = businessCenter;
	}

}