// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

public class CalculationAmount extends Money implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<Step> step;
	
    
	/**
     * public getter
     *
     * A schedule of step date and value pairs. On each step date the associated step value becomes effective. A list of steps may be ordered in the document by ascending step date. An FpML document containing an unordered list of steps is still regarded as a conformant document.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.Step>
	 */
	public List<Step> getStep() {
	    return this.step;
	}
	
	/**
	 * public setter
	 *
     * A schedule of step date and value pairs. On each step date the associated step value becomes effective. A list of steps may be ordered in the document by ascending step date. An FpML document containing an unordered list of steps is still regarded as a conformant document.
     *
     * @param java.util.List<com.leansoft.fpml.nano.Step>
	 */
	public void setStep(List<Step> step) {
	    this.step = step;
	}

}