// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The unit in which a commission is denominated.
 */
public enum CommissionDenominationEnum {

    /**
     * The commission is expressed in basis points, in reference to the price referenced in the document.
     */
    BPS("BPS"),
  

    /**
     * The commission is expressed as a percentage of the gross price referenced in the document.
     */
    PERCENTAGE("Percentage"),
  

    /**
     * The commission is expressed in cents per share.
     */
    CENTS_PER_SHARE("CentsPerShare"),
  

    /**
     * The commission is expressed as a absolute amount.
     */
    FIXED_AMOUNT("FixedAmount");
  
  
    private final String value;
  
    CommissionDenominationEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static CommissionDenominationEnum fromValue(String v) {
        if (v != null) {
            for (CommissionDenominationEnum c: CommissionDenominationEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}