// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A Notification that a Novation event is cancelled.
 */
@RootElement(name = "contractNovatedCancelled", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class ContractNovatedCancelled extends NotificationMessage implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private ContractReference contractReference;
	
	@Element
	private ContractNovation novation;
	
	@Element
	private List<Party> party;
	
    
	/**
     * public getter
     *
     * Reference to the contract affected by the cancellation.
     *
     * @returns com.leansoft.fpml.nano.ContractReference
	 */
	public ContractReference getContractReference() {
	    return this.contractReference;
	}
	
	/**
	 * public setter
	 *
     * Reference to the contract affected by the cancellation.
     *
     * @param com.leansoft.fpml.nano.ContractReference
	 */
	public void setContractReference(ContractReference contractReference) {
	    this.contractReference = contractReference;
	}
	/**
     * public getter
     *
     * Details of the Novation being cancelled.
     *
     * @returns com.leansoft.fpml.nano.ContractNovation
	 */
	public ContractNovation getNovation() {
	    return this.novation;
	}
	
	/**
	 * public setter
	 *
     * Details of the Novation being cancelled.
     *
     * @param com.leansoft.fpml.nano.ContractNovation
	 */
	public void setNovation(ContractNovation novation) {
	    this.novation = novation;
	}
	/**
     * public getter
     *
     * Identification of the Parties to this Contract.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * Identification of the Parties to this Contract.
     *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}