// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * Notification that a Contract has been Increased
 */
@RootElement(name = "contractIncreased", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class ContractIncreased extends NotificationMessage implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private ChangeContractSize increase;
	
	@Element
	private List<Party> party;
	
    
	/**
     * public getter
     *
     * Increase Details.
     *
     * @returns com.leansoft.fpml.nano.ChangeContractSize
	 */
	public ChangeContractSize getIncrease() {
	    return this.increase;
	}
	
	/**
	 * public setter
	 *
     * Increase Details.
     *
     * @param com.leansoft.fpml.nano.ChangeContractSize
	 */
	public void setIncrease(ChangeContractSize increase) {
	    this.increase = increase;
	}
	/**
     * public getter
     *
     * Identification of the Parties to this Contract.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * Identification of the Parties to this Contract.
     *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}