// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Details of the Contract Novation
 */
public class ContractNovation implements Serializable {

    private static final long serialVersionUID = -1L;

    

}