// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "basketCurrency", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class Currency implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String currencyScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getCurrencyScheme() {
	    return this.currencyScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setCurrencyScheme(String currencyScheme) {
	    this.currencyScheme = currencyScheme;
	}

}