// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * List of DateTimes
 */
public class DateTimeList implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<Date> dateTime;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<java.util.Date>
	 */
	public List<Date> getDateTime() {
	    return this.dateTime;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<java.util.Date>
	 */
	public void setDateTime(List<Date> dateTime) {
	    this.dateTime = dateTime;
	}

}