// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * List of Dates
 */
public class DateList implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<Date> date;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<java.util.Date>
	 */
	public List<Date> getDate() {
	    return this.date;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<java.util.Date>
	 */
	public void setDate(List<Date> date) {
	    this.date = date;
	}

}