// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type that allows a position to be defined. It includes identification information (ID and version), trade information, etc.
 */
public class DefinePosition extends Position implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private PositionReference forceMatch;
	
    
	/**
     * public getter
     *
     * An optional reference to a position supplied by the matching party that is known to match this one.
     *
     * @returns com.leansoft.fpml.nano.PositionReference
	 */
	public PositionReference getForceMatch() {
	    return this.forceMatch;
	}
	
	/**
	 * public setter
	 *
     * An optional reference to a position supplied by the matching party that is known to match this one.
     *
     * @param com.leansoft.fpml.nano.PositionReference
	 */
	public void setForceMatch(PositionReference forceMatch) {
	    this.forceMatch = forceMatch;
	}

}