// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A valuation scenario that is derived from another valuation scenario.
 */
public class DerivedValuationScenario implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private String name;
	
	@Element
	private ValuationScenarioReference baseValuationScenario;
	
	@Element
	private IdentifiedDate valuationDate;
	
	@Element
	private MarketReference marketReference;
	
	@Element
	private List<PricingParameterShift> shift;
	
	@Attribute  
	private String id;
	
    
	/**
     * public getter
     *
     * The (optional) name for this valuation scenario, used for understandability. For example "EOD Valuations".
     *
     * @returns java.lang.String
	 */
	public String getName() {
	    return this.name;
	}
	
	/**
	 * public setter
	 *
     * The (optional) name for this valuation scenario, used for understandability. For example "EOD Valuations".
     *
     * @param java.lang.String
	 */
	public void setName(String name) {
	    this.name = name;
	}
	/**
     * public getter
     *
     * An (optional) reference to a valuation scenario from which this one is derived.
     *
     * @returns com.leansoft.fpml.nano.ValuationScenarioReference
	 */
	public ValuationScenarioReference getBaseValuationScenario() {
	    return this.baseValuationScenario;
	}
	
	/**
	 * public setter
	 *
     * An (optional) reference to a valuation scenario from which this one is derived.
     *
     * @param com.leansoft.fpml.nano.ValuationScenarioReference
	 */
	public void setBaseValuationScenario(ValuationScenarioReference baseValuationScenario) {
	    this.baseValuationScenario = baseValuationScenario;
	}
	/**
     * public getter
     *
     * The (optional) date for which the assets are valued. If not present, the valuation date will be that of the base valuation scenario.
     *
     * @returns com.leansoft.fpml.nano.IdentifiedDate
	 */
	public IdentifiedDate getValuationDate() {
	    return this.valuationDate;
	}
	
	/**
	 * public setter
	 *
     * The (optional) date for which the assets are valued. If not present, the valuation date will be that of the base valuation scenario.
     *
     * @param com.leansoft.fpml.nano.IdentifiedDate
	 */
	public void setValuationDate(IdentifiedDate valuationDate) {
	    this.valuationDate = valuationDate;
	}
	/**
     * public getter
     *
     * A reference to the market environment used to price the asset. If not present, the market will be that of the base valuation scenario.
     *
     * @returns com.leansoft.fpml.nano.MarketReference
	 */
	public MarketReference getMarketReference() {
	    return this.marketReference;
	}
	
	/**
	 * public setter
	 *
     * A reference to the market environment used to price the asset. If not present, the market will be that of the base valuation scenario.
     *
     * @param com.leansoft.fpml.nano.MarketReference
	 */
	public void setMarketReference(MarketReference marketReference) {
	    this.marketReference = marketReference;
	}
	/**
     * public getter
     *
     * A collection of shifts to be applied to market inputs prior to computation of the derivative.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.PricingParameterShift>
	 */
	public List<PricingParameterShift> getShift() {
	    return this.shift;
	}
	
	/**
	 * public setter
	 *
     * A collection of shifts to be applied to market inputs prior to computation of the derivative.
     *
     * @param java.util.List<com.leansoft.fpml.nano.PricingParameterShift>
	 */
	public void setShift(List<PricingParameterShift> shift) {
	    this.shift = shift;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}