// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The ISDA defined value indicating the severity of a difference.
 */
public enum DifferenceSeverityEnum {

    WARNING("Warning"),
  

    ERROR("Error");
  
  
    private final String value;
  
    DifferenceSeverityEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static DifferenceSeverityEnum fromValue(String v) {
        if (v != null) {
            for (DifferenceSeverityEnum c: DifferenceSeverityEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}