// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * An abstract base class for all directional leg types with effective date, termination date, and underlyer, where a payer makes a stream of payments of greater than zero value to a receiver.
 */
public abstract class DirectionalLegUnderlyerValuation extends DirectionalLegUnderlyer implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private EquityValuation valuation;
	
    
	/**
     * public getter
     *
     * Valuation of the underlyer.
     *
     * @returns com.leansoft.fpml.nano.EquityValuation
	 */
	public EquityValuation getValuation() {
	    return this.valuation;
	}
	
	/**
	 * public setter
	 *
     * Valuation of the underlyer.
     *
     * @param com.leansoft.fpml.nano.EquityValuation
	 */
	public void setValuation(EquityValuation valuation) {
	    this.valuation = valuation;
	}

}