// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The date on which the receiver of the equity return is entitled to the dividend.
 */
public enum DividendEntitlementEnum {

    /**
     * Dividend entitlement is on the dividend ex-date.
     */
    EX_DATE("ExDate"),
  

    /**
     * Dividend entitlement is on the dividend record date.
     */
    RECORD_DATE("RecordDate");
  
  
    private final String value;
  
    DividendEntitlementEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static DividendEntitlementEnum fromValue(String v) {
        if (v != null) {
            for (DividendEntitlementEnum c: DividendEntitlementEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}