// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A Dividend Swap Transaction Supplement.
 */
@RootElement(name = "dividendSwapTransactionSupplement", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class DividendSwapTransactionSupplement extends Product implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private DividendLeg dividendLeg;
	
	@Element
	private FixedPaymentLeg fixedLeg;
	
    
	/**
     * public getter
     *
     * Dividend leg.
     *
     * @returns com.leansoft.fpml.nano.DividendLeg
	 */
	public DividendLeg getDividendLeg() {
	    return this.dividendLeg;
	}
	
	/**
	 * public setter
	 *
     * Dividend leg.
     *
     * @param com.leansoft.fpml.nano.DividendLeg
	 */
	public void setDividendLeg(DividendLeg dividendLeg) {
	    this.dividendLeg = dividendLeg;
	}
	/**
     * public getter
     *
     * Fixed payment leg.
     *
     * @returns com.leansoft.fpml.nano.FixedPaymentLeg
	 */
	public FixedPaymentLeg getFixedLeg() {
	    return this.fixedLeg;
	}
	
	/**
	 * public setter
	 *
     * Fixed payment leg.
     *
     * @param com.leansoft.fpml.nano.FixedPaymentLeg
	 */
	public void setFixedLeg(FixedPaymentLeg fixedLeg) {
	    this.fixedLeg = fixedLeg;
	}

}