// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * An Option on a Dividend Swap Transaction Supplement.
 */
@RootElement(name = "dividendSwapTransactionSupplementOption", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class DividendSwapTransactionSupplementOption extends OptionBaseExtended implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private OptionStrike strike;
	
	@Element
	private DividendSwapTransactionSupplement dividendSwapTransactionSupplement;
	
    
	/**
     * public getter
     *
     * Strike of the Dividend Swap Transaction Supplement.
     *
     * @returns com.leansoft.fpml.nano.OptionStrike
	 */
	public OptionStrike getStrike() {
	    return this.strike;
	}
	
	/**
	 * public setter
	 *
     * Strike of the Dividend Swap Transaction Supplement.
     *
     * @param com.leansoft.fpml.nano.OptionStrike
	 */
	public void setStrike(OptionStrike strike) {
	    this.strike = strike;
	}
	/**
     * public getter
     *
     * Dividend Swap Transaction Supplement which is the underlyer of this Option.
     *
     * @returns com.leansoft.fpml.nano.DividendSwapTransactionSupplement
	 */
	public DividendSwapTransactionSupplement getDividendSwapTransactionSupplement() {
	    return this.dividendSwapTransactionSupplement;
	}
	
	/**
	 * public setter
	 *
     * Dividend Swap Transaction Supplement which is the underlyer of this Option.
     *
     * @param com.leansoft.fpml.nano.DividendSwapTransactionSupplement
	 */
	public void setDividendSwapTransactionSupplement(DividendSwapTransactionSupplement dividendSwapTransactionSupplement) {
	    this.dividendSwapTransactionSupplement = dividendSwapTransactionSupplement;
	}

}