// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * Lender portion of the drawdown payment
 */
public class DrawdownPayment implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Date paymentDate;
	
	@Element
	private Money shareLoanContractAmount;
	
    
	/**
     * public getter
     *
     * The date on which the principal payment is made by the leder to the agent bank. Usually defaults to the effective date of the loan contract.
     *
     * @returns java.util.Date
	 */
	public Date getPaymentDate() {
	    return this.paymentDate;
	}
	
	/**
	 * public setter
	 *
     * The date on which the principal payment is made by the leder to the agent bank. Usually defaults to the effective date of the loan contract.
     *
     * @param java.util.Date
	 */
	public void setPaymentDate(Date paymentDate) {
	    this.paymentDate = paymentDate;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.Money
	 */
	public Money getShareLoanContractAmount() {
	    return this.shareLoanContractAmount;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.Money
	 */
	public void setShareLoanContractAmount(Money shareLoanContractAmount) {
	    this.shareLoanContractAmount = shareLoanContractAmount;
	}

}