// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * The name of the reference entity. A free format string. FpML does not define usage rules for this element.
 */
@RootElement(name = "entityName", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class EntityName implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String entityNameScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getEntityNameScheme() {
	    return this.entityNameScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setEntityNameScheme(String entityNameScheme) {
	    this.entityNameScheme = entityNameScheme;
	}

}