// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * An exchange traded equity asset.
 */
@RootElement(name = "equity", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class EquityAsset extends ExchangeTraded implements Serializable {

    private static final long serialVersionUID = -1L;

    

}