// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type defining the basic structure of FpML business events; it is refined by its derived types.
 */
@RootElement(name = "event", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public abstract class Event implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<EventId> eventId;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.EventId>
	 */
	public List<EventId> getEventId() {
	    return this.eventId;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.EventId>
	 */
	public void setEventId(List<EventId> eventId) {
	    this.eventId = eventId;
	}

}