// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * A type defining the trade execution date time and the source of it. For use inside containing types which already have a Reference to a Party that has assigned this trade execution date time.
 */
public class ExecutionDateTime implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private Date value;
	
	@Attribute  
	private String executionDateTimeScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.Date
	 */
	public Date getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.Date
	 */
	public void setValue(Date value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getExecutionDateTimeScheme() {
	    return this.executionDateTimeScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setExecutionDateTimeScheme(String executionDateTimeScheme) {
	    this.executionDateTimeScheme = executionDateTimeScheme;
	}

}