// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type describing how notice of exercise should be given. This can be either manual or automatic.
 */
public class ExerciseProcedure implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private ManualExercise manualExercise;
	
	@Element
	private AutomaticExercise automaticExercise;
	
	@Element
	private boolean followUpConfirmation;
	
	@Element
	private Boolean limitedRightToConfirm;
	
	@Element
	private Boolean splitTicket;
	
    
	/**
     * public getter
     *
     * Specifies that the notice of exercise must be given by the buyer to the seller or seller's agent.
     *
     * @returns com.leansoft.fpml.nano.ManualExercise
	 */
	public ManualExercise getManualExercise() {
	    return this.manualExercise;
	}
	
	/**
	 * public setter
	 *
     * Specifies that the notice of exercise must be given by the buyer to the seller or seller's agent.
     *
     * @param com.leansoft.fpml.nano.ManualExercise
	 */
	public void setManualExercise(ManualExercise manualExercise) {
	    this.manualExercise = manualExercise;
	}
	/**
     * public getter
     *
     * If automatic is specified then the notional amount of the underlying swap, not previously exercised under the swaption will be automatically exercised at the expriration time on the expiration date if at such time the buyer is in-the-money, provided that the difference between the settlement rate and the fixed rate under the relevant underlying swap is not less than the specified threshold rate. The term in-the-money is assumed to have the meaning defining in the 2000 ISDA Definitions, Section 17.4 In-the-money.
     *
     * @returns com.leansoft.fpml.nano.AutomaticExercise
	 */
	public AutomaticExercise getAutomaticExercise() {
	    return this.automaticExercise;
	}
	
	/**
	 * public setter
	 *
     * If automatic is specified then the notional amount of the underlying swap, not previously exercised under the swaption will be automatically exercised at the expriration time on the expiration date if at such time the buyer is in-the-money, provided that the difference between the settlement rate and the fixed rate under the relevant underlying swap is not less than the specified threshold rate. The term in-the-money is assumed to have the meaning defining in the 2000 ISDA Definitions, Section 17.4 In-the-money.
     *
     * @param com.leansoft.fpml.nano.AutomaticExercise
	 */
	public void setAutomaticExercise(AutomaticExercise automaticExercise) {
	    this.automaticExercise = automaticExercise;
	}
	/**
     * public getter
     *
     * A flag to indicate whether follow-up confirmation of exercise (written or electronic) is required following telephonic notice by the buyer to the seller or seller's agent.
     *
     * @returns .boolean
	 */
	public boolean getFollowUpConfirmation() {
	    return this.followUpConfirmation;
	}
	
	/**
	 * public setter
	 *
     * A flag to indicate whether follow-up confirmation of exercise (written or electronic) is required following telephonic notice by the buyer to the seller or seller's agent.
     *
     * @param .boolean
	 */
	public void setFollowUpConfirmation(boolean followUpConfirmation) {
	    this.followUpConfirmation = followUpConfirmation;
	}
	/**
     * public getter
     *
     * Has the meaning defined as part of the 1997 ISDA Government Bond Option Definitions, section 4.5 Limited Right to Confirm Exercise. If present, (i) the Seller may request the Buyer to confirm its intent if not done on or before the expiration time on the Expiration date (ii) specific rules will apply in relation to the settlement mode.
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getLimitedRightToConfirm() {
	    return this.limitedRightToConfirm;
	}
	
	/**
	 * public setter
	 *
     * Has the meaning defined as part of the 1997 ISDA Government Bond Option Definitions, section 4.5 Limited Right to Confirm Exercise. If present, (i) the Seller may request the Buyer to confirm its intent if not done on or before the expiration time on the Expiration date (ii) specific rules will apply in relation to the settlement mode.
     *
     * @param java.lang.Boolean
	 */
	public void setLimitedRightToConfirm(Boolean limitedRightToConfirm) {
	    this.limitedRightToConfirm = limitedRightToConfirm;
	}
	/**
     * public getter
     *
     * Typically applicable to the physical settlement of bond and convertible bond options. If present, means that the Party required to deliver the bonds will divide those to be delivered as notifying party desires to facilitate delivery obligations.
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getSplitTicket() {
	    return this.splitTicket;
	}
	
	/**
	 * public setter
	 *
     * Typically applicable to the physical settlement of bond and convertible bond options. If present, means that the Party required to deliver the bonds will divide those to be delivered as notifying party desires to facilitate delivery obligations.
     *
     * @param java.lang.Boolean
	 */
	public void setSplitTicket(Boolean splitTicket) {
	    this.splitTicket = splitTicket;
	}

}