// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Fixed payment amount within a Dividend Swap.
 */
public class FixedPaymentAmount implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Money paymentAmount;
	
	@Element
	private RelativeDateOffset paymentDate;
	
    
	/**
     * public getter
     *
     * Payment amount, which is optional since the payment amount may be calculated using fixed strike and number of open units.
     *
     * @returns com.leansoft.fpml.nano.Money
	 */
	public Money getPaymentAmount() {
	    return this.paymentAmount;
	}
	
	/**
	 * public setter
	 *
     * Payment amount, which is optional since the payment amount may be calculated using fixed strike and number of open units.
     *
     * @param com.leansoft.fpml.nano.Money
	 */
	public void setPaymentAmount(Money paymentAmount) {
	    this.paymentAmount = paymentAmount;
	}
	/**
     * public getter
     *
     * Payment date relative to another date.
     *
     * @returns com.leansoft.fpml.nano.RelativeDateOffset
	 */
	public RelativeDateOffset getPaymentDate() {
	    return this.paymentDate;
	}
	
	/**
	 * public setter
	 *
     * Payment date relative to another date.
     *
     * @param com.leansoft.fpml.nano.RelativeDateOffset
	 */
	public void setPaymentDate(RelativeDateOffset paymentDate) {
	    this.paymentDate = paymentDate;
	}

}