// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type defining a rate index.
 */
public class ForecastRateIndex implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private FloatingRateIndex floatingRateIndex;
	
	@Element
	private Interval indexTenor;
	
    
	/**
     * public getter
     *
     * The ISDA Floating Rate Option, i.e. the floating rate index.
     *
     * @returns com.leansoft.fpml.nano.FloatingRateIndex
	 */
	public FloatingRateIndex getFloatingRateIndex() {
	    return this.floatingRateIndex;
	}
	
	/**
	 * public setter
	 *
     * The ISDA Floating Rate Option, i.e. the floating rate index.
     *
     * @param com.leansoft.fpml.nano.FloatingRateIndex
	 */
	public void setFloatingRateIndex(FloatingRateIndex floatingRateIndex) {
	    this.floatingRateIndex = floatingRateIndex;
	}
	/**
     * public getter
     *
     * The ISDA Designated Maturity, i.e. the tenor of the floating rate.
     *
     * @returns com.leansoft.fpml.nano.Interval
	 */
	public Interval getIndexTenor() {
	    return this.indexTenor;
	}
	
	/**
	 * public setter
	 *
     * The ISDA Designated Maturity, i.e. the tenor of the floating rate.
     *
     * @param com.leansoft.fpml.nano.Interval
	 */
	public void setIndexTenor(Interval indexTenor) {
	    this.indexTenor = indexTenor;
	}

}