// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Frequency Type
 */
public class FrequencyType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String frequencyTypeScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getFrequencyTypeScheme() {
	    return this.frequencyTypeScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setFrequencyTypeScheme(String frequencyTypeScheme) {
	    this.frequencyTypeScheme = frequencyTypeScheme;
	}

}