// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type that is used for describing cash settlement of an option / non deliverable forward. It includes the currency to settle into together with the fixings required to calculate the currency amount.
 */
public class FxCashSettlement implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Currency settlementCurrency;
	
	@Element
	private List<FxFixing> fixing;
	
    
	/**
     * public getter
     *
     * The currency in which a cash settlement for non-deliverable forward and non-deliverable options.
     *
     * @returns com.leansoft.fpml.nano.Currency
	 */
	public Currency getSettlementCurrency() {
	    return this.settlementCurrency;
	}
	
	/**
	 * public setter
	 *
     * The currency in which a cash settlement for non-deliverable forward and non-deliverable options.
     *
     * @param com.leansoft.fpml.nano.Currency
	 */
	public void setSettlementCurrency(Currency settlementCurrency) {
	    this.settlementCurrency = settlementCurrency;
	}
	/**
     * public getter
     *
     * Specifies the source for and timing of a fixing of an exchange rate. This is used in the agreement of non-deliverable forward trades as well as various types of FX OTC options that require observations against a particular rate.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.FxFixing>
	 */
	public List<FxFixing> getFixing() {
	    return this.fixing;
	}
	
	/**
	 * public setter
	 *
     * Specifies the source for and timing of a fixing of an exchange rate. This is used in the agreement of non-deliverable forward trades as well as various types of FX OTC options that require observations against a particular rate.
     *
     * @param java.util.List<com.leansoft.fpml.nano.FxFixing>
	 */
	public void setFixing(List<FxFixing> fixing) {
	    this.fixing = fixing;
	}

}