// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type for defining Fx Features.
 */
public class FxFeature implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private IdentifiedCurrency referenceCurrency;
	
	@Element
	private Composite composite;
	
	@Element
	private Quanto quanto;
	
	@Element
	private Composite crossCurrency;
	
    
	/**
     * public getter
     *
     * Specifies the reference currency of the trade.
     *
     * @returns com.leansoft.fpml.nano.IdentifiedCurrency
	 */
	public IdentifiedCurrency getReferenceCurrency() {
	    return this.referenceCurrency;
	}
	
	/**
	 * public setter
	 *
     * Specifies the reference currency of the trade.
     *
     * @param com.leansoft.fpml.nano.IdentifiedCurrency
	 */
	public void setReferenceCurrency(IdentifiedCurrency referenceCurrency) {
	    this.referenceCurrency = referenceCurrency;
	}
	/**
     * public getter
     *
     * If “Composite” is specified as the Settlement Type in the relevant Transaction Supplement, an amount in the Settlement Currency, determined by the Calculation Agent as being equal to the number of Options exercised or deemed exercised, multiplied by: (Settlement Price – Strike Price) / (Strike Price – Settlement Price) x Multiplier provided that if the above is equal to a negative amount the Option Cash Settlement Amount shall be deemed to be zero.
     *
     * @returns com.leansoft.fpml.nano.Composite
	 */
	public Composite getComposite() {
	    return this.composite;
	}
	
	/**
	 * public setter
	 *
     * If “Composite” is specified as the Settlement Type in the relevant Transaction Supplement, an amount in the Settlement Currency, determined by the Calculation Agent as being equal to the number of Options exercised or deemed exercised, multiplied by: (Settlement Price – Strike Price) / (Strike Price – Settlement Price) x Multiplier provided that if the above is equal to a negative amount the Option Cash Settlement Amount shall be deemed to be zero.
     *
     * @param com.leansoft.fpml.nano.Composite
	 */
	public void setComposite(Composite composite) {
	    this.composite = composite;
	}
	/**
     * public getter
     *
     * If “Quanto” is specified as the Settlement Type in the relevant Transaction Supplement, an amount, as determined by the Calculation Agent in accordance with the Section 8.2 of the Equity Definitions
     *
     * @returns com.leansoft.fpml.nano.Quanto
	 */
	public Quanto getQuanto() {
	    return this.quanto;
	}
	
	/**
	 * public setter
	 *
     * If “Quanto” is specified as the Settlement Type in the relevant Transaction Supplement, an amount, as determined by the Calculation Agent in accordance with the Section 8.2 of the Equity Definitions
     *
     * @param com.leansoft.fpml.nano.Quanto
	 */
	public void setQuanto(Quanto quanto) {
	    this.quanto = quanto;
	}
	/**
     * public getter
     *
     * If “Cross-Currency” is specified as the Settlement Type in the relevant Transaction Supplement, an amount in the Settlement Currency, determined by the Calculation Agent as being equal to the number of Options exercised or deemed exercised, multiplied by: (Settlement Price – Strike Price) / (Strike Price – Settlement Price) x Multiplier x one unit of the Reference Currency converted into an amount in the Settlement Currency using the rate of exchange of the Settlement Currency as quoted on the Reference Price Source on the Valuation Date, provided that if the above is equal to a negative amount the Option Cash Settlement Amount shall be deemed to be zero
     *
     * @returns com.leansoft.fpml.nano.Composite
	 */
	public Composite getCrossCurrency() {
	    return this.crossCurrency;
	}
	
	/**
	 * public setter
	 *
     * If “Cross-Currency” is specified as the Settlement Type in the relevant Transaction Supplement, an amount in the Settlement Currency, determined by the Calculation Agent as being equal to the number of Options exercised or deemed exercised, multiplied by: (Settlement Price – Strike Price) / (Strike Price – Settlement Price) x Multiplier x one unit of the Reference Currency converted into an amount in the Settlement Currency using the rate of exchange of the Settlement Currency as quoted on the Reference Price Source on the Valuation Date, provided that if the above is equal to a negative amount the Option Cash Settlement Amount shall be deemed to be zero
     *
     * @param com.leansoft.fpml.nano.Composite
	 */
	public void setCrossCurrency(Composite crossCurrency) {
	    this.crossCurrency = crossCurrency;
	}

}