// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * A type to describe the cashflow representation for fx linked notionals.
 */
public class FxLinkedNotionalAmount implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Date resetDate;
	
	@Element
	private Date adjustedFxSpotFixingDate;
	
	@Element
	private BigDecimal observedFxSpotRate;
	
	@Element
	private BigDecimal notionalAmount;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.Date
	 */
	public Date getResetDate() {
	    return this.resetDate;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.Date
	 */
	public void setResetDate(Date resetDate) {
	    this.resetDate = resetDate;
	}
	/**
     * public getter
     *
     * The date on which the fx spot rate is observed. This date should already be adjusted for any applicable business day convention.
     *
     * @returns java.util.Date
	 */
	public Date getAdjustedFxSpotFixingDate() {
	    return this.adjustedFxSpotFixingDate;
	}
	
	/**
	 * public setter
	 *
     * The date on which the fx spot rate is observed. This date should already be adjusted for any applicable business day convention.
     *
     * @param java.util.Date
	 */
	public void setAdjustedFxSpotFixingDate(Date adjustedFxSpotFixingDate) {
	    this.adjustedFxSpotFixingDate = adjustedFxSpotFixingDate;
	}
	/**
     * public getter
     *
     * The actual observed fx spot rate.
     *
     * @returns java.math.BigDecimal
	 */
	public BigDecimal getObservedFxSpotRate() {
	    return this.observedFxSpotRate;
	}
	
	/**
	 * public setter
	 *
     * The actual observed fx spot rate.
     *
     * @param java.math.BigDecimal
	 */
	public void setObservedFxSpotRate(BigDecimal observedFxSpotRate) {
	    this.observedFxSpotRate = observedFxSpotRate;
	}
	/**
     * public getter
     *
     * The calculation period notional amount.
     *
     * @returns java.math.BigDecimal
	 */
	public BigDecimal getNotionalAmount() {
	    return this.notionalAmount;
	}
	
	/**
	 * public setter
	 *
     * The calculation period notional amount.
     *
     * @param java.math.BigDecimal
	 */
	public void setNotionalAmount(BigDecimal notionalAmount) {
	    this.notionalAmount = notionalAmount;
	}

}