// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "fxRate", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class FxRateAsset extends UnderlyingAsset implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private QuotedCurrencyPair quotedCurrencyPair;
	
	@Element
	private FxSpotRateSource rateSource;
	
    
	/**
     * public getter
     *
     * Defines the two currencies for an FX trade and the quotation relationship between the two currencies.
     *
     * @returns com.leansoft.fpml.nano.QuotedCurrencyPair
	 */
	public QuotedCurrencyPair getQuotedCurrencyPair() {
	    return this.quotedCurrencyPair;
	}
	
	/**
	 * public setter
	 *
     * Defines the two currencies for an FX trade and the quotation relationship between the two currencies.
     *
     * @param com.leansoft.fpml.nano.QuotedCurrencyPair
	 */
	public void setQuotedCurrencyPair(QuotedCurrencyPair quotedCurrencyPair) {
	    this.quotedCurrencyPair = quotedCurrencyPair;
	}
	/**
     * public getter
     *
     * Defines the source of the FX rate.
     *
     * @returns com.leansoft.fpml.nano.FxSpotRateSource
	 */
	public FxSpotRateSource getRateSource() {
	    return this.rateSource;
	}
	
	/**
	 * public setter
	 *
     * Defines the source of the FX rate.
     *
     * @param com.leansoft.fpml.nano.FxSpotRateSource
	 */
	public void setRateSource(FxSpotRateSource rateSource) {
	    this.rateSource = rateSource;
	}

}