// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type that describes an FX swap. This is similar to FpML_FXLeg, but contains multiple legs for a particular trade.
 */
@RootElement(name = "fxSwap", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class FxSwap extends Product implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<FxLeg> fxSingleLeg;
	
    
	/**
     * public getter
     *
     * A single-legged FX transaction definition (e.g., spot or forward).
     *
     * @returns java.util.List<com.leansoft.fpml.nano.FxLeg>
	 */
	public List<FxLeg> getFxSingleLeg() {
	    return this.fxSingleLeg;
	}
	
	/**
	 * public setter
	 *
     * A single-legged FX transaction definition (e.g., spot or forward).
     *
     * @param java.util.List<com.leansoft.fpml.nano.FxLeg>
	 */
	public void setFxSingleLeg(List<FxLeg> fxSingleLeg) {
	    this.fxSingleLeg = fxSingleLeg;
	}

}