// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigDecimal;

/**
 * A type defining the components specifiying an Inflation Rate Calculation
 */
@RootElement(name = "inflationRateCalculation", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class InflationRateCalculation extends FloatingRateCalculation implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Offset inflationLag;
	
	@Element
	private RateSourcePage indexSource;
	
	@Element
	private MainPublication mainPublication;
	
	@Element
	private InterpolationMethod interpolationMethod;
	
	@Element
	private BigDecimal initialIndexLevel;
	
    
	/**
     * public getter
     *
     * an offsetting period from the payment date which determines the reference period for which the inflation index is onserved.
     *
     * @returns com.leansoft.fpml.nano.Offset
	 */
	public Offset getInflationLag() {
	    return this.inflationLag;
	}
	
	/**
	 * public setter
	 *
     * an offsetting period from the payment date which determines the reference period for which the inflation index is onserved.
     *
     * @param com.leansoft.fpml.nano.Offset
	 */
	public void setInflationLag(Offset inflationLag) {
	    this.inflationLag = inflationLag;
	}
	/**
     * public getter
     *
     * The reference source such as Reuters or Bloomberg.
     *
     * @returns com.leansoft.fpml.nano.RateSourcePage
	 */
	public RateSourcePage getIndexSource() {
	    return this.indexSource;
	}
	
	/**
	 * public setter
	 *
     * The reference source such as Reuters or Bloomberg.
     *
     * @param com.leansoft.fpml.nano.RateSourcePage
	 */
	public void setIndexSource(RateSourcePage indexSource) {
	    this.indexSource = indexSource;
	}
	/**
     * public getter
     *
     * The current main publication source such as relevant web site or a government body.
     *
     * @returns com.leansoft.fpml.nano.MainPublication
	 */
	public MainPublication getMainPublication() {
	    return this.mainPublication;
	}
	
	/**
	 * public setter
	 *
     * The current main publication source such as relevant web site or a government body.
     *
     * @param com.leansoft.fpml.nano.MainPublication
	 */
	public void setMainPublication(MainPublication mainPublication) {
	    this.mainPublication = mainPublication;
	}
	/**
     * public getter
     *
     * The method used when calculating the Inflation Index Level from multiple points - the most common is Linear.
     *
     * @returns com.leansoft.fpml.nano.InterpolationMethod
	 */
	public InterpolationMethod getInterpolationMethod() {
	    return this.interpolationMethod;
	}
	
	/**
	 * public setter
	 *
     * The method used when calculating the Inflation Index Level from multiple points - the most common is Linear.
     *
     * @param com.leansoft.fpml.nano.InterpolationMethod
	 */
	public void setInterpolationMethod(InterpolationMethod interpolationMethod) {
	    this.interpolationMethod = interpolationMethod;
	}
	/**
     * public getter
     *
     * initial known index level for the first calculation period.
     *
     * @returns java.math.BigDecimal
	 */
	public BigDecimal getInitialIndexLevel() {
	    return this.initialIndexLevel;
	}
	
	/**
	 * public setter
	 *
     * initial known index level for the first calculation period.
     *
     * @param java.math.BigDecimal
	 */
	public void setInitialIndexLevel(BigDecimal initialIndexLevel) {
	    this.initialIndexLevel = initialIndexLevel;
	}

}