// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type defining the source for a piece of information (e.g. a rate refix or an fx fixing).
 */
public class InformationSource implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private InformationProvider rateSource;
	
	@Element
	private RateSourcePage rateSourcePage;
	
	@Element
	private String rateSourcePageHeading;
	
    
	/**
     * public getter
     *
     * An information source for obtaining a market rate. For example Bloomberg, Reuters, Telerate etc.
     *
     * @returns com.leansoft.fpml.nano.InformationProvider
	 */
	public InformationProvider getRateSource() {
	    return this.rateSource;
	}
	
	/**
	 * public setter
	 *
     * An information source for obtaining a market rate. For example Bloomberg, Reuters, Telerate etc.
     *
     * @param com.leansoft.fpml.nano.InformationProvider
	 */
	public void setRateSource(InformationProvider rateSource) {
	    this.rateSource = rateSource;
	}
	/**
     * public getter
     *
     * A specific page for the rate source for obtaining a market rate.
     *
     * @returns com.leansoft.fpml.nano.RateSourcePage
	 */
	public RateSourcePage getRateSourcePage() {
	    return this.rateSourcePage;
	}
	
	/**
	 * public setter
	 *
     * A specific page for the rate source for obtaining a market rate.
     *
     * @param com.leansoft.fpml.nano.RateSourcePage
	 */
	public void setRateSourcePage(RateSourcePage rateSourcePage) {
	    this.rateSourcePage = rateSourcePage;
	}
	/**
     * public getter
     *
     * The heading for the rate source on a given rate source page.
     *
     * @returns java.lang.String
	 */
	public String getRateSourcePageHeading() {
	    return this.rateSourcePageHeading;
	}
	
	/**
	 * public setter
	 *
     * The heading for the rate source on a given rate source page.
     *
     * @param java.lang.String
	 */
	public void setRateSourcePageHeading(String rateSourcePageHeading) {
	    this.rateSourcePageHeading = rateSourcePageHeading;
	}

}