// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Specifies the calculation method of the interest rate leg of the equity swap. Includes the floating or fixed rate calculation definitions, along with the determination of the day count fraction.
 */
public class InterestCalculation extends InterestAccrualsMethod implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private DayCountFraction dayCountFraction;
	
	@Element
	private Compounding compounding;
	
	@Attribute  
	private String id;
	
    
	/**
     * public getter
     *
     * The day count fraction.
     *
     * @returns com.leansoft.fpml.nano.DayCountFraction
	 */
	public DayCountFraction getDayCountFraction() {
	    return this.dayCountFraction;
	}
	
	/**
	 * public setter
	 *
     * The day count fraction.
     *
     * @param com.leansoft.fpml.nano.DayCountFraction
	 */
	public void setDayCountFraction(DayCountFraction dayCountFraction) {
	    this.dayCountFraction = dayCountFraction;
	}
	/**
     * public getter
     *
     * Defines compounding rates on the Interest Leg.
     *
     * @returns com.leansoft.fpml.nano.Compounding
	 */
	public Compounding getCompounding() {
	    return this.compounding;
	}
	
	/**
	 * public setter
	 *
     * Defines compounding rates on the Interest Leg.
     *
     * @param com.leansoft.fpml.nano.Compounding
	 */
	public void setCompounding(Compounding compounding) {
	    this.compounding = compounding;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}