// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * A period within which the lender maintains certain position amount.
 */
public class LenderPositionPeriod implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Date startDate;
	
	@Element
	private Date endDate;
	
	@Element
	private ParticipationAmount positionAmount;
	
    
	/**
     * public getter
     *
     * Date on which this period begins.
     *
     * @returns java.util.Date
	 */
	public Date getStartDate() {
	    return this.startDate;
	}
	
	/**
	 * public setter
	 *
     * Date on which this period begins.
     *
     * @param java.util.Date
	 */
	public void setStartDate(Date startDate) {
	    this.startDate = startDate;
	}
	/**
     * public getter
     *
     * Date on which this period ends.
     *
     * @returns java.util.Date
	 */
	public Date getEndDate() {
	    return this.endDate;
	}
	
	/**
	 * public setter
	 *
     * Date on which this period ends.
     *
     * @param java.util.Date
	 */
	public void setEndDate(Date endDate) {
	    this.endDate = endDate;
	}
	/**
     * public getter
     *
     * Global and lender share amounts.
     *
     * @returns com.leansoft.fpml.nano.ParticipationAmount
	 */
	public ParticipationAmount getPositionAmount() {
	    return this.positionAmount;
	}
	
	/**
	 * public setter
	 *
     * Global and lender share amounts.
     *
     * @param com.leansoft.fpml.nano.ParticipationAmount
	 */
	public void setPositionAmount(ParticipationAmount positionAmount) {
	    this.positionAmount = positionAmount;
	}

}