// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;
import java.util.Date;

/**
 * A basic set of fields to identify the loan contract
 */
public class LoanContractIdentifier implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<ContractIdentifier> identifier;
	
	@Element
	private Money originalAmount;
	
	@Element
	private Date maturityDate;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.ContractIdentifier>
	 */
	public List<ContractIdentifier> getIdentifier() {
	    return this.identifier;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.ContractIdentifier>
	 */
	public void setIdentifier(List<ContractIdentifier> identifier) {
	    this.identifier = identifier;
	}
	/**
     * public getter
     *
     * Original amount associated with the loan contract in loan contract currency.
     *
     * @returns com.leansoft.fpml.nano.Money
	 */
	public Money getOriginalAmount() {
	    return this.originalAmount;
	}
	
	/**
	 * public setter
	 *
     * Original amount associated with the loan contract in loan contract currency.
     *
     * @param com.leansoft.fpml.nano.Money
	 */
	public void setOriginalAmount(Money originalAmount) {
	    this.originalAmount = originalAmount;
	}
	/**
     * public getter
     *
     * Maturity date of the loan contract. In the case of an ABR loan this field should be set to the maturity date of the facility.>
     *
     * @returns java.util.Date
	 */
	public Date getMaturityDate() {
	    return this.maturityDate;
	}
	
	/**
	 * public setter
	 *
     * Maturity date of the loan contract. In the case of an ABR loan this field should be set to the maturity date of the facility.>
     *
     * @param java.util.Date
	 */
	public void setMaturityDate(Date maturityDate) {
	    this.maturityDate = maturityDate;
	}

}