// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

@RootElement(name = "Manifest", namespace = "http://www.w3.org/2000/09/xmldsig#")
public class ManifestType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Reference")
	private List<ReferenceType> reference;
	
	@Attribute(name = "Id")
	private String id;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.ReferenceType>
	 */
	public List<ReferenceType> getReference() {
	    return this.reference;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.ReferenceType>
	 */
	public void setReference(List<ReferenceType> reference) {
	    this.reference = reference;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}