// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Defines the handling of an averaging date market disruption for an equity derivative transaction.
 */
public class MarketDisruption implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String marketDisruptionScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getMarketDisruptionScheme() {
	    return this.marketDisruptionScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setMarketDisruptionScheme(String marketDisruptionScheme) {
	    this.marketDisruptionScheme = marketDisruptionScheme;
	}

}