// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type defining the basic structure of all FpML messages which is refined by its derived types.
 */
public abstract class Message extends Document implements Serializable {

    private static final long serialVersionUID = -1L;

    

}