// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * Defines how adjustments will be made to the contract should one or more of the extraordinary events occur.
 */
public enum MethodOfAdjustmentEnum {

    /**
     * The Calculation Agent has the right to adjust the terms of the trade following a corporate action.
     */
    CALCULATION_AGENT("CalculationAgent"),
  

    /**
     * The trade will be adjusted in accordance with any adjustment made by the exchange on which options on the underlying are listed.
     */
    OPTIONS_EXCHANGE("OptionsExchange");
  
  
    private final String value;
  
    MethodOfAdjustmentEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static MethodOfAdjustmentEnum fromValue(String v) {
        if (v != null) {
            for (MethodOfAdjustmentEnum c: MethodOfAdjustmentEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}