// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "mutualFund", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class MutualFund extends UnderlyingAsset implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Boolean openEndedFund;
	
	@Element
	private String fundManager;
	
    
	/**
     * public getter
     *
     * Boolean indicator to specify whether the mutual fund is an open-ended mutual fund.
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getOpenEndedFund() {
	    return this.openEndedFund;
	}
	
	/**
	 * public setter
	 *
     * Boolean indicator to specify whether the mutual fund is an open-ended mutual fund.
     *
     * @param java.lang.Boolean
	 */
	public void setOpenEndedFund(Boolean openEndedFund) {
	    this.openEndedFund = openEndedFund;
	}
	/**
     * public getter
     *
     * Specifies the fund manager that is in charge of the fund.
     *
     * @returns java.lang.String
	 */
	public String getFundManager() {
	    return this.fundManager;
	}
	
	/**
	 * public setter
	 *
     * Specifies the fund manager that is in charge of the fund.
     *
     * @param java.lang.String
	 */
	public void setFundManager(String fundManager) {
	    this.fundManager = fundManager;
	}

}