// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type defining the parameters used when the reference currency of the swapStream is non-deliverable.
 */
public class NonDeliverableSettlement implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Currency referenceCurrency;
	
	@Element
	private FxFixingDate fxFixingDate;
	
	@Element
	private SettlementRateOption settlementRateOption;
	
	@Element
	private PriceSourceDisruption priceSourceDisruption;
	
    
	/**
     * public getter
     *
     * The currency in which the swap stream is denominated in.
     *
     * @returns com.leansoft.fpml.nano.Currency
	 */
	public Currency getReferenceCurrency() {
	    return this.referenceCurrency;
	}
	
	/**
	 * public setter
	 *
     * The currency in which the swap stream is denominated in.
     *
     * @param com.leansoft.fpml.nano.Currency
	 */
	public void setReferenceCurrency(Currency referenceCurrency) {
	    this.referenceCurrency = referenceCurrency;
	}
	/**
     * public getter
     *
     * The fixing date(s) on which the currency rate will be determined for the purpose of specifying the amount in deliverable currency.
     *
     * @returns com.leansoft.fpml.nano.FxFixingDate
	 */
	public FxFixingDate getFxFixingDate() {
	    return this.fxFixingDate;
	}
	
	/**
	 * public setter
	 *
     * The fixing date(s) on which the currency rate will be determined for the purpose of specifying the amount in deliverable currency.
     *
     * @param com.leansoft.fpml.nano.FxFixingDate
	 */
	public void setFxFixingDate(FxFixingDate fxFixingDate) {
	    this.fxFixingDate = fxFixingDate;
	}
	/**
     * public getter
     *
     * The rate source for the conversion to the settlement currency. This source is specified through a scheme that reflects the terms of the Annex A to the 1998 FX and Currency Option Definitions.
     *
     * @returns com.leansoft.fpml.nano.SettlementRateOption
	 */
	public SettlementRateOption getSettlementRateOption() {
	    return this.settlementRateOption;
	}
	
	/**
	 * public setter
	 *
     * The rate source for the conversion to the settlement currency. This source is specified through a scheme that reflects the terms of the Annex A to the 1998 FX and Currency Option Definitions.
     *
     * @param com.leansoft.fpml.nano.SettlementRateOption
	 */
	public void setSettlementRateOption(SettlementRateOption settlementRateOption) {
	    this.settlementRateOption = settlementRateOption;
	}
	/**
     * public getter
     *
     * A type defining the parameters to get a new quote when a settlement rate option is disrupted.
     *
     * @returns com.leansoft.fpml.nano.PriceSourceDisruption
	 */
	public PriceSourceDisruption getPriceSourceDisruption() {
	    return this.priceSourceDisruption;
	}
	
	/**
	 * public setter
	 *
     * A type defining the parameters to get a new quote when a settlement rate option is disrupted.
     *
     * @param com.leansoft.fpml.nano.PriceSourceDisruption
	 */
	public void setPriceSourceDisruption(PriceSourceDisruption priceSourceDisruption) {
	    this.priceSourceDisruption = priceSourceDisruption;
	}

}