// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * An type defining the notional amount or notional amount schedule associated with a swap stream. The notional schedule will be captured explicitly, specifying the dates that the notional changes and the outstanding notional amount that applies from that date. A parametric representation of the rules defining the notional step schedule can optionally be included.
 */
public class Notional implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private AmountSchedule notionalStepSchedule;
	
	@Element
	private NotionalStepRule notionalStepParameters;
	
	@Attribute  
	private String id;
	
    
	/**
     * public getter
     *
     * The notional amount or notional amount schedule expressed as explicit outstanding notional amounts and dates. In the case of a schedule, the step dates may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments.
     *
     * @returns com.leansoft.fpml.nano.AmountSchedule
	 */
	public AmountSchedule getNotionalStepSchedule() {
	    return this.notionalStepSchedule;
	}
	
	/**
	 * public setter
	 *
     * The notional amount or notional amount schedule expressed as explicit outstanding notional amounts and dates. In the case of a schedule, the step dates may be subject to adjustment in accordance with any adjustments specified in calculationPeriodDatesAdjustments.
     *
     * @param com.leansoft.fpml.nano.AmountSchedule
	 */
	public void setNotionalStepSchedule(AmountSchedule notionalStepSchedule) {
	    this.notionalStepSchedule = notionalStepSchedule;
	}
	/**
     * public getter
     *
     * A parametric representation of the notional step schedule, i.e. parameters used to generate the notional schedule.
     *
     * @returns com.leansoft.fpml.nano.NotionalStepRule
	 */
	public NotionalStepRule getNotionalStepParameters() {
	    return this.notionalStepParameters;
	}
	
	/**
	 * public setter
	 *
     * A parametric representation of the notional step schedule, i.e. parameters used to generate the notional schedule.
     *
     * @param com.leansoft.fpml.nano.NotionalStepRule
	 */
	public void setNotionalStepParameters(NotionalStepRule notionalStepParameters) {
	    this.notionalStepParameters = notionalStepParameters;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}