// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Response message that should be sent by the transferee or remaining party if they cannot perform the requested novation.
 */
@RootElement(name = "novationConsentRefused", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class NovationConsentRefused extends NovationResponseMessage implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Reason reason;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.Reason
	 */
	public Reason getReason() {
	    return this.reason;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.Reason
	 */
	public void setReason(Reason reason) {
	    this.reason = reason;
	}

}