// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Response message that should be sent by the receiving parties if they agree with the novation. The transferee or transferor party may include the details of a payment representing the market value of the transaction.
 */
@RootElement(name = "novationConsentGranted", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class NovationConsentGranted extends NovationResponseMessage implements Serializable {

    private static final long serialVersionUID = -1L;

    

}