// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * There are cases where the borrower may be required to make a one-off fee payment. This will usually be based on a certain business event occurring. The rules as to how much is charged will be stated in the credit agreement. The only fee type covered in this section is amendment Fee: A fee charged to the borrower for an amendment being made to the originally agreed credit agreement. The fee is based on a rate (as stated in the agreement) applied to the current commitment level.
 */
@RootElement(name = "oneOffFeeNotice", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class OneOffFeeNotice extends FacilityNotice implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private LoanContractIdentifier loanContractIdentifier;
	
	@Element
	private OneOffFeePayment feePayment;
	
	@Element
	private List<Party> party;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.LoanContractIdentifier
	 */
	public LoanContractIdentifier getLoanContractIdentifier() {
	    return this.loanContractIdentifier;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.LoanContractIdentifier
	 */
	public void setLoanContractIdentifier(LoanContractIdentifier loanContractIdentifier) {
	    this.loanContractIdentifier = loanContractIdentifier;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.OneOffFeePayment
	 */
	public OneOffFeePayment getFeePayment() {
	    return this.feePayment;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.OneOffFeePayment
	 */
	public void setFeePayment(OneOffFeePayment feePayment) {
	    this.feePayment = feePayment;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}