// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * The agent bank will request that the borrower makes a fee payment in accordance with the credit agreement. The borrower will make a payment to the agent bank after which the agent bank will calculate each lenders fee amounts. It is important to note that these fees are all calculated based on facility level information. The fee types are Commitment Fee, Utilization Fee, Facility Fee, Letter of Credit Fee.
 */
@RootElement(name = "onGoingFeeNotice", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class OnGoingFeeNotice extends FacilityNotice implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private OnGoingFeePayment feePayment;
	
	@Element
	private FeeAccrualSchedule feeAccrualSchedule;
	
	@Element
	private List<Party> party;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.OnGoingFeePayment
	 */
	public OnGoingFeePayment getFeePayment() {
	    return this.feePayment;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.OnGoingFeePayment
	 */
	public void setFeePayment(OnGoingFeePayment feePayment) {
	    this.feePayment = feePayment;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.FeeAccrualSchedule
	 */
	public FeeAccrualSchedule getFeeAccrualSchedule() {
	    return this.feeAccrualSchedule;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.FeeAccrualSchedule
	 */
	public void setFeeAccrualSchedule(FeeAccrualSchedule feeAccrualSchedule) {
	    this.feeAccrualSchedule = feeAccrualSchedule;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}