// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigDecimal;

/**
 * A type for defining the strike price for an option as a numeric value without currency.
 */
public class OptionNumericStrike implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private BigDecimal strikePrice;
	
	@Element
	private BigDecimal strikePercentage;
	
    
	/**
     * public getter
     *
     * The price or level at which the option has been struck.
     *
     * @returns java.math.BigDecimal
	 */
	public BigDecimal getStrikePrice() {
	    return this.strikePrice;
	}
	
	/**
	 * public setter
	 *
     * The price or level at which the option has been struck.
     *
     * @param java.math.BigDecimal
	 */
	public void setStrikePrice(BigDecimal strikePrice) {
	    this.strikePrice = strikePrice;
	}
	/**
     * public getter
     *
     * The price or level expressed as a percentage of the forward starting spot price.
     *
     * @returns java.math.BigDecimal
	 */
	public BigDecimal getStrikePercentage() {
	    return this.strikePercentage;
	}
	
	/**
	 * public setter
	 *
     * The price or level expressed as a percentage of the forward starting spot price.
     *
     * @param java.math.BigDecimal
	 */
	public void setStrikePercentage(BigDecimal strikePercentage) {
	    this.strikePercentage = strikePercentage;
	}

}