// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type defining the adjusted dates associated with an optional early termination provision.
 */
public class OptionalEarlyTerminationAdjustedDates implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<EarlyTerminationEvent> earlyTerminationEvent;
	
    
	/**
     * public getter
     *
     * The adjusted dates associated with an individual earley termination date.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.EarlyTerminationEvent>
	 */
	public List<EarlyTerminationEvent> getEarlyTerminationEvent() {
	    return this.earlyTerminationEvent;
	}
	
	/**
	 * public setter
	 *
     * The adjusted dates associated with an individual earley termination date.
     *
     * @param java.util.List<com.leansoft.fpml.nano.EarlyTerminationEvent>
	 */
	public void setEarlyTerminationEvent(List<EarlyTerminationEvent> earlyTerminationEvent) {
	    this.earlyTerminationEvent = earlyTerminationEvent;
	}

}