// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Generic type to capture global and share amounts
 */
public class ParticipationAmount implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Money globalAmount;
	
	@Element
	private Money shareAmount;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.Money
	 */
	public Money getGlobalAmount() {
	    return this.globalAmount;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.Money
	 */
	public void setGlobalAmount(Money globalAmount) {
	    this.globalAmount = globalAmount;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.Money
	 */
	public Money getShareAmount() {
	    return this.shareAmount;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.Money
	 */
	public void setShareAmount(Money shareAmount) {
	    this.shareAmount = shareAmount;
	}

}