// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type defining one or more trade identifiers allocated to the trade by a party. A link identifier allows the trade to be associated with other related trades, e.g. trades forming part of a larger structured transaction. It is expected that for external communication of trade there will be only one tradeId sent in the document per party.
 */
public class PartyTradeIdentifier extends TradeIdentifier implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<LinkId> linkId;
	
    
	/**
     * public getter
     *
     * A link identifier allowing the trade to be associated with other related trades, e.g. the linkId may contain a tradeId for an associated trade or several related trades may be given the same linkId. FpML does not define the domain values associated with this element. Note that the domain values for this element are not strictly an enumerated list.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.LinkId>
	 */
	public List<LinkId> getLinkId() {
	    return this.linkId;
	}
	
	/**
	 * public setter
	 *
     * A link identifier allowing the trade to be associated with other related trades, e.g. the linkId may contain a tradeId for an associated trade or several related trades may be given the same linkId. FpML does not define the domain values associated with this element. Note that the domain values for this element are not strictly an enumerated list.
     *
     * @param java.util.List<com.leansoft.fpml.nano.LinkId>
	 */
	public void setLinkId(List<LinkId> linkId) {
	    this.linkId = linkId;
	}

}