// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type containing multiple partyTradeIdentifier.
 */
@RootElement(name = "newTransactionReference", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class PartyTradeIdentifiers implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<PartyTradeIdentifier> partyTradeIdentifier;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.PartyTradeIdentifier>
	 */
	public List<PartyTradeIdentifier> getPartyTradeIdentifier() {
	    return this.partyTradeIdentifier;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.PartyTradeIdentifier>
	 */
	public void setPartyTradeIdentifier(List<PartyTradeIdentifier> partyTradeIdentifier) {
	    this.partyTradeIdentifier = partyTradeIdentifier;
	}

}