// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The specification of an interest rate stream payer or receiver party.
 */
public enum PayerReceiverEnum {

    /**
     * The party identified as the stream payer.
     */
    PAYER("Payer"),
  

    /**
     * The party identified as the stream receiver.
     */
    RECEIVER("Receiver");
  
  
    private final String value;
  
    PayerReceiverEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static PayerReceiverEnum fromValue(String v) {
        if (v != null) {
            for (PayerReceiverEnum c: PayerReceiverEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}