// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * An identifier used to identify a matchable payment.
 */
public class PaymentId implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String paymentIdScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getPaymentIdScheme() {
	    return this.paymentIdScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setPaymentIdScheme(String paymentIdScheme) {
	    this.paymentIdScheme = paymentIdScheme;
	}

}