// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type representing an arbitary grouping of trade references.
 */
@RootElement(name = "portfolio", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class Portfolio implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private PartyPortfolioName partyPortfolioName;
	
	@Element
	private List<TradeId> tradeId;
	
	@Element
	private List<Portfolio> portfolio;
	
	@Attribute  
	private String id;
	
    
	/**
     * public getter
     *
     * The name of the portfolio together with the party that gave the name.
     *
     * @returns com.leansoft.fpml.nano.PartyPortfolioName
	 */
	public PartyPortfolioName getPartyPortfolioName() {
	    return this.partyPortfolioName;
	}
	
	/**
	 * public setter
	 *
     * The name of the portfolio together with the party that gave the name.
     *
     * @param com.leansoft.fpml.nano.PartyPortfolioName
	 */
	public void setPartyPortfolioName(PartyPortfolioName partyPortfolioName) {
	    this.partyPortfolioName = partyPortfolioName;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.TradeId>
	 */
	public List<TradeId> getTradeId() {
	    return this.tradeId;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.TradeId>
	 */
	public void setTradeId(List<TradeId> tradeId) {
	    this.tradeId = tradeId;
	}
	/**
     * public getter
     *
     * An arbitary grouping of trade references (and possibly other portfolios).
     *
     * @returns java.util.List<com.leansoft.fpml.nano.Portfolio>
	 */
	public List<Portfolio> getPortfolio() {
	    return this.portfolio;
	}
	
	/**
	 * public setter
	 *
     * An arbitary grouping of trade references (and possibly other portfolios).
     *
     * @param java.util.List<com.leansoft.fpml.nano.Portfolio>
	 */
	public void setPortfolio(List<Portfolio> portfolio) {
	    this.portfolio = portfolio;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}