// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.Date;

/**
 * The set of elements that identify a portfolio.
 */
public class PortfolioDefinition implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private String portfolioName;
	
	@Element
	private Date asOfDate;
	
	@Element
	private PartyReference definingParty;
	
	@Element
	private PartyReference matchingParty;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getPortfolioName() {
	    return this.portfolioName;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setPortfolioName(String portfolioName) {
	    this.portfolioName = portfolioName;
	}
	/**
	 * public getter
	 *
     * @returns java.util.Date
	 */
	public Date getAsOfDate() {
	    return this.asOfDate;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.Date
	 */
	public void setAsOfDate(Date asOfDate) {
	    this.asOfDate = asOfDate;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.PartyReference
	 */
	public PartyReference getDefiningParty() {
	    return this.definingParty;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.PartyReference
	 */
	public void setDefiningParty(PartyReference definingParty) {
	    this.definingParty = definingParty;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.PartyReference
	 */
	public PartyReference getMatchingParty() {
	    return this.matchingParty;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.PartyReference
	 */
	public void setMatchingParty(PartyReference matchingParty) {
	    this.matchingParty = matchingParty;
	}

}