// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * The units in which a price is quoted.
 */
public class PriceQuoteUnits implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String priceQuoteUnitsScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getPriceQuoteUnitsScheme() {
	    return this.priceQuoteUnitsScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setPriceQuoteUnitsScheme(String priceQuoteUnitsScheme) {
	    this.priceQuoteUnitsScheme = priceQuoteUnitsScheme;
	}

}