// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * For an asset (e.g. a reference/benchmark asset), the pricing structure used to price it. Used, for example, to specify that the rateIndex "USD-LIBOR-Telerate" with term = 6M is priced using the "USD-LIBOR-Close" curve.
 */
public class PricingMethod implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private AnyAssetReference assetReference;
	
	@Element
	private PricingStructureReference pricingInputReference;
	
    
	/**
     * public getter
     *
     * The asset whose price is required.
     *
     * @returns com.leansoft.fpml.nano.AnyAssetReference
	 */
	public AnyAssetReference getAssetReference() {
	    return this.assetReference;
	}
	
	/**
	 * public setter
	 *
     * The asset whose price is required.
     *
     * @param com.leansoft.fpml.nano.AnyAssetReference
	 */
	public void setAssetReference(AnyAssetReference assetReference) {
	    this.assetReference = assetReference;
	}
	/**
     * public getter
     *
     * A reference to the pricing input used to value the asset.
     *
     * @returns com.leansoft.fpml.nano.PricingStructureReference
	 */
	public PricingStructureReference getPricingInputReference() {
	    return this.pricingInputReference;
	}
	
	/**
	 * public setter
	 *
     * A reference to the pricing input used to value the asset.
     *
     * @param com.leansoft.fpml.nano.PricingStructureReference
	 */
	public void setPricingInputReference(PricingStructureReference pricingInputReference) {
	    this.pricingInputReference = pricingInputReference;
	}

}