// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type representing a portfolio obtained by querying the set of trades held in a repository. It contains trades matching the intersection of all criteria specified using one or more queryParameters or trades matching the union of two or more child queryPortfolios.
 */
@RootElement(name = "queryPortfolio", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class QueryPortfolio extends Portfolio implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private List<QueryParameter> queryParameter;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.QueryParameter>
	 */
	public List<QueryParameter> getQueryParameter() {
	    return this.queryParameter;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.QueryParameter>
	 */
	public void setQueryParameter(List<QueryParameter> queryParameter) {
	    this.queryParameter = queryParameter;
	}

}