// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type representing an identifier for a parameter describing a query portfolio. An identifier can be anything from a product name like swap to a termination date.
 */
public class QueryParameterId implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String queryParameterIdScheme;
	
	@Attribute  
	private String id;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getQueryParameterIdScheme() {
	    return this.queryParameterIdScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setQueryParameterIdScheme(String queryParameterIdScheme) {
	    this.queryParameterIdScheme = queryParameterIdScheme;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}