// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * How an exchange rate is quoted.
 */
public enum QuoteBasisEnum {

    /**
     * The amount of currency1 for one unit of currency2
     */
    CURRENCY_1_PER_CURRENCY_2("Currency1PerCurrency2"),
  

    /**
     * The amount of currency2 for one unit of currency1
     */
    CURRENCY_2_PER_CURRENCY_1("Currency2PerCurrency1");
  
  
    private final String value;
  
    QuoteBasisEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static QuoteBasisEnum fromValue(String v) {
        if (v != null) {
            for (QuoteBasisEnum c: QuoteBasisEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}