// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Rate information per rate period
 */
public class RatePeriod implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Date startDate;
	
	@Element
	private Date endDate;
	
	@Element
	private BigDecimal rate;
	
    
	/**
     * public getter
     *
     * Date on which this period begins.
     *
     * @returns java.util.Date
	 */
	public Date getStartDate() {
	    return this.startDate;
	}
	
	/**
	 * public setter
	 *
     * Date on which this period begins.
     *
     * @param java.util.Date
	 */
	public void setStartDate(Date startDate) {
	    this.startDate = startDate;
	}
	/**
     * public getter
     *
     * Date on which this period ends.
     *
     * @returns java.util.Date
	 */
	public Date getEndDate() {
	    return this.endDate;
	}
	
	/**
	 * public setter
	 *
     * Date on which this period ends.
     *
     * @param java.util.Date
	 */
	public void setEndDate(Date endDate) {
	    this.endDate = endDate;
	}
	/**
     * public getter
     *
     * >Rate for this period
     *
     * @returns java.math.BigDecimal
	 */
	public BigDecimal getRate() {
	    return this.rate;
	}
	
	/**
	 * public setter
	 *
     * >Rate for this period
     *
     * @param java.math.BigDecimal
	 */
	public void setRate(BigDecimal rate) {
	    this.rate = rate;
	}

}