// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * The abstract base class for all types which define interest rate streams.
 */
@RootElement(name = "rateCalculation", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public abstract class Rate implements Serializable {

    private static final long serialVersionUID = -1L;

	@Attribute  
	private String id;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}