// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The contract specifies whether which price must satisfy the boundary condition.
 */
public enum RealisedVarianceMethodEnum {

    /**
     * For a return on day T, the observed price on T-1 must be in range.
     */
    PREVIOUS("Previous"),
  

    /**
     * For a return on day T, the observed price on T must be in range.
     */
    LAST("Last"),
  

    /**
     * For a return on day T, the observed prices on both T and T-1 must be in range
     */
    BOTH("Both");
  
  
    private final String value;
  
    RealisedVarianceMethodEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static RealisedVarianceMethodEnum fromValue(String v) {
        if (v != null) {
            for (RealisedVarianceMethodEnum c: RealisedVarianceMethodEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}