// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type defining a content model for describing the nature and possible location of a error within a previous message.
 */
public class Reason implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private ReasonCode reasonCode;
	
	@Element
	private ProblemLocation location;
	
	@Element
	private String description;
	
	@Element
	private Validation validationRuleId;
	
	@Element
	private List<AdditionalData> additionalData;
	
    
	/**
     * public getter
     *
     * A machine interpretable error code.
     *
     * @returns com.leansoft.fpml.nano.ReasonCode
	 */
	public ReasonCode getReasonCode() {
	    return this.reasonCode;
	}
	
	/**
	 * public setter
	 *
     * A machine interpretable error code.
     *
     * @param com.leansoft.fpml.nano.ReasonCode
	 */
	public void setReasonCode(ReasonCode reasonCode) {
	    this.reasonCode = reasonCode;
	}
	/**
     * public getter
     *
     * A value indicating the location of the problem within the subject message.
     *
     * @returns com.leansoft.fpml.nano.ProblemLocation
	 */
	public ProblemLocation getLocation() {
	    return this.location;
	}
	
	/**
	 * public setter
	 *
     * A value indicating the location of the problem within the subject message.
     *
     * @param com.leansoft.fpml.nano.ProblemLocation
	 */
	public void setLocation(ProblemLocation location) {
	    this.location = location;
	}
	/**
     * public getter
     *
     * Plain English text describing the associated error condition
     *
     * @returns java.lang.String
	 */
	public String getDescription() {
	    return this.description;
	}
	
	/**
	 * public setter
	 *
     * Plain English text describing the associated error condition
     *
     * @param java.lang.String
	 */
	public void setDescription(String description) {
	    this.description = description;
	}
	/**
     * public getter
     *
     * A reference identifying a rule within a validation scheme
     *
     * @returns com.leansoft.fpml.nano.Validation
	 */
	public Validation getValidationRuleId() {
	    return this.validationRuleId;
	}
	
	/**
	 * public setter
	 *
     * A reference identifying a rule within a validation scheme
     *
     * @param com.leansoft.fpml.nano.Validation
	 */
	public void setValidationRuleId(Validation validationRuleId) {
	    this.validationRuleId = validationRuleId;
	}
	/**
     * public getter
     *
     * Any string of additional data that may help the message processor, for example in a rejection message this might contain a code value or the text of any one of the messages (within a CDATA section).
     *
     * @returns java.util.List<com.leansoft.fpml.nano.AdditionalData>
	 */
	public List<AdditionalData> getAdditionalData() {
	    return this.additionalData;
	}
	
	/**
	 * public setter
	 *
     * Any string of additional data that may help the message processor, for example in a rejection message this might contain a code value or the text of any one of the messages (within a CDATA section).
     *
     * @param java.util.List<com.leansoft.fpml.nano.AdditionalData>
	 */
	public void setAdditionalData(List<AdditionalData> additionalData) {
	    this.additionalData = additionalData;
	}

}