// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type describing a date when this date is defined in reference to another date through one or several date offsets.
 */
public class RelativeDateSequence implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private DateReference dateRelativeTo;
	
	@Element
	private List<DateOffset> dateOffset;
	
	@Element
	private BusinessCentersReference businessCentersReference;
	
	@Element
	private BusinessCenters businessCenters;
	
    
	/**
     * public getter
     *
     * Specifies the anchor as an href attribute. The href attribute value is a pointer style reference to the element or component elsewhere in the document where the anchor date is defined.
     *
     * @returns com.leansoft.fpml.nano.DateReference
	 */
	public DateReference getDateRelativeTo() {
	    return this.dateRelativeTo;
	}
	
	/**
	 * public setter
	 *
     * Specifies the anchor as an href attribute. The href attribute value is a pointer style reference to the element or component elsewhere in the document where the anchor date is defined.
     *
     * @param com.leansoft.fpml.nano.DateReference
	 */
	public void setDateRelativeTo(DateReference dateRelativeTo) {
	    this.dateRelativeTo = dateRelativeTo;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.DateOffset>
	 */
	public List<DateOffset> getDateOffset() {
	    return this.dateOffset;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.DateOffset>
	 */
	public void setDateOffset(List<DateOffset> dateOffset) {
	    this.dateOffset = dateOffset;
	}
	/**
     * public getter
     *
     * A pointer style reference to a set of financial business centers defined elsewhere in the document. This set of business centers is used to determine whether a particular day is a business day or not.
     *
     * @returns com.leansoft.fpml.nano.BusinessCentersReference
	 */
	public BusinessCentersReference getBusinessCentersReference() {
	    return this.businessCentersReference;
	}
	
	/**
	 * public setter
	 *
     * A pointer style reference to a set of financial business centers defined elsewhere in the document. This set of business centers is used to determine whether a particular day is a business day or not.
     *
     * @param com.leansoft.fpml.nano.BusinessCentersReference
	 */
	public void setBusinessCentersReference(BusinessCentersReference businessCentersReference) {
	    this.businessCentersReference = businessCentersReference;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.BusinessCenters
	 */
	public BusinessCenters getBusinessCenters() {
	    return this.businessCenters;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.BusinessCenters
	 */
	public void setBusinessCenters(BusinessCenters businessCenters) {
	    this.businessCenters = businessCenters;
	}

}