// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A loan repayment notice.
 */
@RootElement(name = "repaymentNotice", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class RepaymentNotice extends FacilityNotice implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Repayment repayment;
	
	@Element
	private List<Party> party;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.Repayment
	 */
	public Repayment getRepayment() {
	    return this.repayment;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.Repayment
	 */
	public void setRepayment(Repayment repayment) {
	    this.repayment = repayment;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}