// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * Lender share of the borrower re-payment
 */
public class Repayment implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private FacilityRepayment facilityRepayment;
	
	@Element
	private List<LoanContractRepayment> loanContractRepayment;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.FacilityRepayment
	 */
	public FacilityRepayment getFacilityRepayment() {
	    return this.facilityRepayment;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.FacilityRepayment
	 */
	public void setFacilityRepayment(FacilityRepayment facilityRepayment) {
	    this.facilityRepayment = facilityRepayment;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.LoanContractRepayment>
	 */
	public List<LoanContractRepayment> getLoanContractRepayment() {
	    return this.loanContractRepayment;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.LoanContractRepayment>
	 */
	public void setLoanContractRepayment(List<LoanContractRepayment> loanContractRepayment) {
	    this.loanContractRepayment = loanContractRepayment;
	}

}