// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * Message used in order to initiate the allocation process.
 */
@RootElement(name = "requestAllocation", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class RequestAllocation extends RequestMessage implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private BlockTradeIdentifier blockTradeIdentifier;
	
	@Element
	private Allocations allocations;
	
	@Element
	private List<Party> party;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.BlockTradeIdentifier
	 */
	public BlockTradeIdentifier getBlockTradeIdentifier() {
	    return this.blockTradeIdentifier;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.BlockTradeIdentifier
	 */
	public void setBlockTradeIdentifier(BlockTradeIdentifier blockTradeIdentifier) {
	    this.blockTradeIdentifier = blockTradeIdentifier;
	}
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.Allocations
	 */
	public Allocations getAllocations() {
	    return this.allocations;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.Allocations
	 */
	public void setAllocations(Allocations allocations) {
	    this.allocations = allocations;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}