// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Specifies the notional of return type swap. When used in the equity leg, the definition will typically combine the actual amount (using the notional component defined by the FpML industry group) and the determination method. When used in the interest leg, the definition will typically point to the definition of the equity leg.
 */
public class ReturnSwapNotional implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private AmountReference amountRelativeTo;
	
	@Element
	private DeterminationMethod determinationMethod;
	
	@Element
	private Money notionalAmount;
	
	@Attribute  
	private String id;
	
    
	/**
     * public getter
     *
     * Reference to an amount defined elsewhere in this document.
     *
     * @returns com.leansoft.fpml.nano.AmountReference
	 */
	public AmountReference getAmountRelativeTo() {
	    return this.amountRelativeTo;
	}
	
	/**
	 * public setter
	 *
     * Reference to an amount defined elsewhere in this document.
     *
     * @param com.leansoft.fpml.nano.AmountReference
	 */
	public void setAmountRelativeTo(AmountReference amountRelativeTo) {
	    this.amountRelativeTo = amountRelativeTo;
	}
	/**
     * public getter
     *
     * Specifies the method according to which an amount or a date is determined.
     *
     * @returns com.leansoft.fpml.nano.DeterminationMethod
	 */
	public DeterminationMethod getDeterminationMethod() {
	    return this.determinationMethod;
	}
	
	/**
	 * public setter
	 *
     * Specifies the method according to which an amount or a date is determined.
     *
     * @param com.leansoft.fpml.nano.DeterminationMethod
	 */
	public void setDeterminationMethod(DeterminationMethod determinationMethod) {
	    this.determinationMethod = determinationMethod;
	}
	/**
     * public getter
     *
     * The notional amount.
     *
     * @returns com.leansoft.fpml.nano.Money
	 */
	public Money getNotionalAmount() {
	    return this.notionalAmount;
	}
	
	/**
	 * public setter
	 *
     * The notional amount.
     *
     * @param com.leansoft.fpml.nano.Money
	 */
	public void setNotionalAmount(Money notionalAmount) {
	    this.notionalAmount = notionalAmount;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}