// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The type of return associated with the equity swap.
 */
public enum ReturnTypeEnum {

    /**
     * Dividend return swap.
     */
    DIVIDEND("Dividend"),
  

    /**
     * Price return swap.
     */
    PRICE("Price"),
  

    /**
     * Total return swap.
     */
    TOTAL("Total");
  
  
    private final String value;
  
    ReturnTypeEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static ReturnTypeEnum fromValue(String v) {
        if (v != null) {
            for (ReturnTypeEnum c: ReturnTypeEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}