// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Specifies, in relation to each Payment Date, the amount to which the Payment Date relates. For Equity Swaps this element is equivalent to the Equity Amount term as defined in the ISDA 2002 Equity Derivatives Definitions.
 */
public class ReturnSwapAmount extends LegAmount implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Boolean cashSettlement;
	
	@Element
	private Boolean optionsExchangeDividends;
	
	@Element
	private Boolean additionalDividends;
	
    
	/**
     * public getter
     *
     * If true, then cash settlement is applicable.
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getCashSettlement() {
	    return this.cashSettlement;
	}
	
	/**
	 * public setter
	 *
     * If true, then cash settlement is applicable.
     *
     * @param java.lang.Boolean
	 */
	public void setCashSettlement(Boolean cashSettlement) {
	    this.cashSettlement = cashSettlement;
	}
	/**
     * public getter
     *
     * If present and true, then options exchange dividends are applicable.
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getOptionsExchangeDividends() {
	    return this.optionsExchangeDividends;
	}
	
	/**
	 * public setter
	 *
     * If present and true, then options exchange dividends are applicable.
     *
     * @param java.lang.Boolean
	 */
	public void setOptionsExchangeDividends(Boolean optionsExchangeDividends) {
	    this.optionsExchangeDividends = optionsExchangeDividends;
	}
	/**
     * public getter
     *
     * If present and true, then additional dividends are applicable.
     *
     * @returns java.lang.Boolean
	 */
	public Boolean getAdditionalDividends() {
	    return this.additionalDividends;
	}
	
	/**
	 * public setter
	 *
     * If present and true, then additional dividends are applicable.
     *
     * @param java.lang.Boolean
	 */
	public void setAdditionalDividends(Boolean additionalDividends) {
	    this.additionalDividends = additionalDividends;
	}

}