// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A collection of sensitivities. References a definition that explains the meaning/type of the sensitivities.
 */
public class SensitivitySet implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private String name;
	
	@Element
	private SensitivitySetReference definitionReference;
	
	@Element
	private List<Sensitivity> sensitivity;
	
	@Attribute  
	private String id;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getName() {
	    return this.name;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setName(String name) {
	    this.name = name;
	}
	/**
     * public getter
     *
     * A reference to a sensitivity set definition.
     *
     * @returns com.leansoft.fpml.nano.SensitivitySetReference
	 */
	public SensitivitySetReference getDefinitionReference() {
	    return this.definitionReference;
	}
	
	/**
	 * public setter
	 *
     * A reference to a sensitivity set definition.
     *
     * @param com.leansoft.fpml.nano.SensitivitySetReference
	 */
	public void setDefinitionReference(SensitivitySetReference definitionReference) {
	    this.definitionReference = definitionReference;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Sensitivity>
	 */
	public List<Sensitivity> getSensitivity() {
	    return this.sensitivity;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Sensitivity>
	 */
	public void setSensitivity(List<Sensitivity> sensitivity) {
	    this.sensitivity = sensitivity;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}