// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * The source from which the settlement price is to be obtained, e.g. a Reuters page, Prezzo di Riferimento, etc.
 */
public class SettlementPriceSource implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String settlementPriceSourceScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getSettlementPriceSourceScheme() {
	    return this.settlementPriceSourceScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setSettlementPriceSourceScheme(String settlementPriceSourceScheme) {
	    this.settlementPriceSourceScheme = settlementPriceSourceScheme;
	}

}