// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type that represents the choice of methods for settling a potential currency payment resulting from a trade: by means of a standard settlement instruction, by netting it out with other payments, or with an explicit settlement instruction.
 */
public class SettlementInformation implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private StandardSettlementStyleEnum standardSettlementStyle;
	
	@Element
	private SettlementInstruction settlementInstruction;
	
    
	/**
     * public getter
     *
     * An optional element used to describe how a trade will settle. This defines a scheme and is used for identifying trades that are identified as settling standard and/or flagged for settlement netting.
     *
     * @returns com.leansoft.fpml.nano.StandardSettlementStyleEnum
	 */
	public StandardSettlementStyleEnum getStandardSettlementStyle() {
	    return this.standardSettlementStyle;
	}
	
	/**
	 * public setter
	 *
     * An optional element used to describe how a trade will settle. This defines a scheme and is used for identifying trades that are identified as settling standard and/or flagged for settlement netting.
     *
     * @param com.leansoft.fpml.nano.StandardSettlementStyleEnum
	 */
	public void setStandardSettlementStyle(StandardSettlementStyleEnum standardSettlementStyle) {
	    this.standardSettlementStyle = standardSettlementStyle;
	}
	/**
     * public getter
     *
     * An explicit specification of how a currency payment is to be made, when the payment is not netted and the route is other than the recipient's standard settlement instruction.
     *
     * @returns com.leansoft.fpml.nano.SettlementInstruction
	 */
	public SettlementInstruction getSettlementInstruction() {
	    return this.settlementInstruction;
	}
	
	/**
	 * public setter
	 *
     * An explicit specification of how a currency payment is to be made, when the payment is not netted and the route is other than the recipient's standard settlement instruction.
     *
     * @param com.leansoft.fpml.nano.SettlementInstruction
	 */
	public void setSettlementInstruction(SettlementInstruction settlementInstruction) {
	    this.settlementInstruction = settlementInstruction;
	}

}