// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "simpleFra", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class SimpleFra extends UnderlyingAsset implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Interval startTerm;
	
	@Element
	private Interval endTerm;
	
	@Element
	private DayCountFraction dayCountFraction;
	
    
	/**
     * public getter
     *
     * Specifies the start term of the simple fra, e.g. 3M.
     *
     * @returns com.leansoft.fpml.nano.Interval
	 */
	public Interval getStartTerm() {
	    return this.startTerm;
	}
	
	/**
	 * public setter
	 *
     * Specifies the start term of the simple fra, e.g. 3M.
     *
     * @param com.leansoft.fpml.nano.Interval
	 */
	public void setStartTerm(Interval startTerm) {
	    this.startTerm = startTerm;
	}
	/**
     * public getter
     *
     * Specifies the end term of the simple fra, e.g. 9M.
     *
     * @returns com.leansoft.fpml.nano.Interval
	 */
	public Interval getEndTerm() {
	    return this.endTerm;
	}
	
	/**
	 * public setter
	 *
     * Specifies the end term of the simple fra, e.g. 9M.
     *
     * @param com.leansoft.fpml.nano.Interval
	 */
	public void setEndTerm(Interval endTerm) {
	    this.endTerm = endTerm;
	}
	/**
     * public getter
     *
     * The day count basis for the FRA.
     *
     * @returns com.leansoft.fpml.nano.DayCountFraction
	 */
	public DayCountFraction getDayCountFraction() {
	    return this.dayCountFraction;
	}
	
	/**
	 * public setter
	 *
     * The day count basis for the FRA.
     *
     * @param com.leansoft.fpml.nano.DayCountFraction
	 */
	public void setDayCountFraction(DayCountFraction dayCountFraction) {
	    this.dayCountFraction = dayCountFraction;
	}

}