// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

@RootElement(name = "SPKIData", namespace = "http://www.w3.org/2000/09/xmldsig#")
public class SPKIDataType implements Serializable {

    private static final long serialVersionUID = -1L;

    

}