// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Defines a Spread Type Scheme to identify a long or short spread value.
 */
public class SpreadScheduleType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String spreadScheduleTypeScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getSpreadScheduleTypeScheme() {
	    return this.spreadScheduleTypeScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setSpreadScheduleTypeScheme(String spreadScheduleTypeScheme) {
	    this.spreadScheduleTypeScheme = spreadScheduleTypeScheme;
	}

}