// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * A type defining a step date and step value pair. This step definitions are used to define varying rate or amount schedules, e.g. a notional amortization or a step-up coupon schedule.
 */
public class Step implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Date stepDate;
	
	@Element
	private BigDecimal stepValue;
	
	@Attribute  
	private String id;
	
    
	/**
     * public getter
     *
     * The date on which the associated stepValue becomes effective. This day may be subject to adjustment in accordance with a business day convention.
     *
     * @returns java.util.Date
	 */
	public Date getStepDate() {
	    return this.stepDate;
	}
	
	/**
	 * public setter
	 *
     * The date on which the associated stepValue becomes effective. This day may be subject to adjustment in accordance with a business day convention.
     *
     * @param java.util.Date
	 */
	public void setStepDate(Date stepDate) {
	    this.stepDate = stepDate;
	}
	/**
     * public getter
     *
     * The rate or amount which becomes effective on the associated stepDate. A rate of 5% would be represented as 0.05.
     *
     * @returns java.math.BigDecimal
	 */
	public BigDecimal getStepValue() {
	    return this.stepValue;
	}
	
	/**
	 * public setter
	 *
     * The rate or amount which becomes effective on the associated stepDate. A rate of 5% would be represented as 0.05.
     *
     * @param java.math.BigDecimal
	 */
	public void setStepValue(BigDecimal stepValue) {
	    this.stepValue = stepValue;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getId() {
	    return this.id;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setId(String id) {
	    this.id = id;
	}

}