// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The specification of how an FX OTC option strike price is quoted.
 */
public enum StrikeQuoteBasisEnum {

    /**
     * The strike price is an amount of putCurrency per one unit of callCurrency.
     */
    PUT_CURRENCY_PER_CALL_CURRENCY("PutCurrencyPerCallCurrency"),
  

    /**
     * The strike price is an amount of callCurrency per one unit of putCurrency.
     */
    CALL_CURRENCY_PER_PUT_CURRENCY("CallCurrencyPerPutCurrency");
  
  
    private final String value;
  
    StrikeQuoteBasisEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static StrikeQuoteBasisEnum fromValue(String v) {
        if (v != null) {
            for (StrikeQuoteBasisEnum c: StrikeQuoteBasisEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}