// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * A type defining how a stub calculation period amount is calculated and the start and end date of the stub. A single floating rate tenor different to that used for the regular part of the calculation periods schedule may be specified, or two floating rate tenors many be specified. If two floating rate tenors are specified then Linear Interpolation (in accordance with the 2000 ISDA Definitions, Section 8.3 Interpolation) is assumed to apply. Alternatively, an actual known stub rate or stub amount may be specified.
 */
@RootElement(name = "finalStub", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class Stub extends StubValue implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private AdjustableOrRelativeDate stubStartDate;
	
	@Element
	private AdjustableOrRelativeDate stubEndDate;
	
    
	/**
     * public getter
     *
     * Start date of stub period. This was created to support use of the InterestRateStream within the Equity Derivative sphere, and this element is not expected to be produced in the representation of Interest Rate products.
     *
     * @returns com.leansoft.fpml.nano.AdjustableOrRelativeDate
	 */
	public AdjustableOrRelativeDate getStubStartDate() {
	    return this.stubStartDate;
	}
	
	/**
	 * public setter
	 *
     * Start date of stub period. This was created to support use of the InterestRateStream within the Equity Derivative sphere, and this element is not expected to be produced in the representation of Interest Rate products.
     *
     * @param com.leansoft.fpml.nano.AdjustableOrRelativeDate
	 */
	public void setStubStartDate(AdjustableOrRelativeDate stubStartDate) {
	    this.stubStartDate = stubStartDate;
	}
	/**
     * public getter
     *
     * End date of stub period. This was created to support use of the InterestRateStream within the Equity Derivative sphere, and this element is not expected to be produced in the representation of Interest Rate products.
     *
     * @returns com.leansoft.fpml.nano.AdjustableOrRelativeDate
	 */
	public AdjustableOrRelativeDate getStubEndDate() {
	    return this.stubEndDate;
	}
	
	/**
	 * public setter
	 *
     * End date of stub period. This was created to support use of the InterestRateStream within the Equity Derivative sphere, and this element is not expected to be produced in the representation of Interest Rate products.
     *
     * @param com.leansoft.fpml.nano.AdjustableOrRelativeDate
	 */
	public void setStubEndDate(AdjustableOrRelativeDate stubEndDate) {
	    this.stubEndDate = stubEndDate;
	}

}