// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigDecimal;

/**
 * A complex type to specify a valuation swap curve, which is used as part of the strike construct for the bond and convertible bond options.
 */
public class SwapCurveValuation implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private FloatingRateIndex floatingRateIndex;
	
	@Element
	private Interval indexTenor;
	
	@Element
	private BigDecimal spread;
	
	@Element
	private QuotationSideEnum side;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.FloatingRateIndex
	 */
	public FloatingRateIndex getFloatingRateIndex() {
	    return this.floatingRateIndex;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.FloatingRateIndex
	 */
	public void setFloatingRateIndex(FloatingRateIndex floatingRateIndex) {
	    this.floatingRateIndex = floatingRateIndex;
	}
	/**
     * public getter
     *
     * The ISDA Designated Maturity, i.e. the tenor of the floating rate.
     *
     * @returns com.leansoft.fpml.nano.Interval
	 */
	public Interval getIndexTenor() {
	    return this.indexTenor;
	}
	
	/**
	 * public setter
	 *
     * The ISDA Designated Maturity, i.e. the tenor of the floating rate.
     *
     * @param com.leansoft.fpml.nano.Interval
	 */
	public void setIndexTenor(Interval indexTenor) {
	    this.indexTenor = indexTenor;
	}
	/**
     * public getter
     *
     * Spread in basis points over the floating rate index.
     *
     * @returns java.math.BigDecimal
	 */
	public BigDecimal getSpread() {
	    return this.spread;
	}
	
	/**
	 * public setter
	 *
     * Spread in basis points over the floating rate index.
     *
     * @param java.math.BigDecimal
	 */
	public void setSpread(BigDecimal spread) {
	    this.spread = spread;
	}
	/**
     * public getter
     *
     * The side (bid/mid/ask) of the measure.
     *
     * @returns com.leansoft.fpml.nano.QuotationSideEnum
	 */
	public QuotationSideEnum getSide() {
	    return this.side;
	}
	
	/**
	 * public setter
	 *
     * The side (bid/mid/ask) of the measure.
     *
     * @param com.leansoft.fpml.nano.QuotationSideEnum
	 */
	public void setSide(QuotationSideEnum side) {
	    this.side = side;
	}

}