// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The specification of, for American-style digitals, whether the trigger level must be touched or not touched.
 */
public enum TouchConditionEnum {

    /**
     * The spot rate must have touched the predetermined trigger rate at any time over the life of the option for the payout to occur.
     */
    TOUCH("Touch"),
  

    /**
     * The spot rate has not touched the predetermined trigger rate at any time over the life of the option for the payout to occur.
     */
    NOTOUCH("Notouch");
  
  
    private final String value;
  
    TouchConditionEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static TouchConditionEnum fromValue(String v) {
        if (v != null) {
            for (TouchConditionEnum c: TouchConditionEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}