// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * The type used to hold TradeStatusScheme values.
 */
public class TradeStatusValue implements Serializable {

    private static final long serialVersionUID = -1L;

	@Value
	private String value;
	
	@Attribute  
	private String tradeStatusScheme;
	
    
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getValue() {
	    return this.value;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setValue(String value) {
	    this.value = value;
	}
	/**
	 * public getter
	 *
     * @returns java.lang.String
	 */
	public String getTradeStatusScheme() {
	    return this.tradeStatusScheme;
	}
	
	/**
	 * public setter
	 *
     * @param java.lang.String
	 */
	public void setTradeStatusScheme(String tradeStatusScheme) {
	    this.tradeStatusScheme = tradeStatusScheme;
	}

}