// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A request message for requesting an Amendment.
 */
@RootElement(name = "tradeAmendmentRequest", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class TradeAmendmentRequest extends RequestMessage implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Amendment amendment;
	
	@Element
	private List<Party> party;
	
    
	/**
	 * public getter
	 *
     * @returns com.leansoft.fpml.nano.Amendment
	 */
	public Amendment getAmendment() {
	    return this.amendment;
	}
	
	/**
	 * public setter
	 *
     * @param com.leansoft.fpml.nano.Amendment
	 */
	public void setAmendment(Amendment amendment) {
	    this.amendment = amendment;
	}
	/**
     * public getter
     *
     * One party element for each of the principal parties and any other party that is referenced.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public List<Party> getParty() {
	    return this.party;
	}
	
	/**
	 * public setter
	 *
     * One party element for each of the principal parties and any other party that is referenced.
     *
     * @param java.util.List<com.leansoft.fpml.nano.Party>
	 */
	public void setParty(List<Party> party) {
	    this.party = party;
	}

}