// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

/**
 * A type describing the original trade and the amended trade.
 */
public class TradeAmendment implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Trade originalTrade;
	
	@Element
	private List<PartyTradeIdentifier> originalTradeIdentifier;
	
	@Element
	private Trade amendedTrade;
	
    
	/**
     * public getter
     *
     * The entire original trade details.
     *
     * @returns com.leansoft.fpml.nano.Trade
	 */
	public Trade getOriginalTrade() {
	    return this.originalTrade;
	}
	
	/**
	 * public setter
	 *
     * The entire original trade details.
     *
     * @param com.leansoft.fpml.nano.Trade
	 */
	public void setOriginalTrade(Trade originalTrade) {
	    this.originalTrade = originalTrade;
	}
	/**
     * public getter
     *
     * The trade id of the original trade details.
     *
     * @returns java.util.List<com.leansoft.fpml.nano.PartyTradeIdentifier>
	 */
	public List<PartyTradeIdentifier> getOriginalTradeIdentifier() {
	    return this.originalTradeIdentifier;
	}
	
	/**
	 * public setter
	 *
     * The trade id of the original trade details.
     *
     * @param java.util.List<com.leansoft.fpml.nano.PartyTradeIdentifier>
	 */
	public void setOriginalTradeIdentifier(List<PartyTradeIdentifier> originalTradeIdentifier) {
	    this.originalTradeIdentifier = originalTradeIdentifier;
	}
	/**
     * public getter
     *
     * The representation of the amended trade.
     *
     * @returns com.leansoft.fpml.nano.Trade
	 */
	public Trade getAmendedTrade() {
	    return this.amendedTrade;
	}
	
	/**
	 * public setter
	 *
     * The representation of the amended trade.
     *
     * @param com.leansoft.fpml.nano.Trade
	 */
	public void setAmendedTrade(Trade amendedTrade) {
	    this.amendedTrade = amendedTrade;
	}

}