// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.util.List;

@RootElement(name = "Transforms", namespace = "http://www.w3.org/2000/09/xmldsig#")
public class TransformsType implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element(name = "Transform")
	private List<TransformType> transform;
	
    
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.TransformType>
	 */
	public List<TransformType> getTransform() {
	    return this.transform;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.TransformType>
	 */
	public void setTransform(List<TransformType> transform) {
	    this.transform = transform;
	}

}