// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;
import java.math.BigInteger;
import java.util.List;

/**
 * A type describing the situation when an entire position change cannot be processed. It includes the position identification information and the reason that the position change could not be processed.
 */
@RootElement(name = "unprocessedPosition", namespace = "http://www.fpml.org/FpML-5-0/reporting")
public class UnprocessedPosition implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private PositionId positionId;
	
	@Element
	private BigInteger version;
	
	@Element
	private List<Reason> reason;
	
    
	/**
     * public getter
     *
     * A version-independent identifier for the position, possibly based on trade identifier.
     *
     * @returns com.leansoft.fpml.nano.PositionId
	 */
	public PositionId getPositionId() {
	    return this.positionId;
	}
	
	/**
	 * public setter
	 *
     * A version-independent identifier for the position, possibly based on trade identifier.
     *
     * @param com.leansoft.fpml.nano.PositionId
	 */
	public void setPositionId(PositionId positionId) {
	    this.positionId = positionId;
	}
	/**
     * public getter
     *
     * A version identifier. Version identifiers must be ascending, i.e. higher numbers imply newer versions. There is no requirement that version identifiers for a position be sequential or small, so for example timestamp-based version identifiers could be used.
     *
     * @returns java.math.BigInteger
	 */
	public BigInteger getVersion() {
	    return this.version;
	}
	
	/**
	 * public setter
	 *
     * A version identifier. Version identifiers must be ascending, i.e. higher numbers imply newer versions. There is no requirement that version identifiers for a position be sequential or small, so for example timestamp-based version identifiers could be used.
     *
     * @param java.math.BigInteger
	 */
	public void setVersion(BigInteger version) {
	    this.version = version;
	}
	/**
	 * public getter
	 *
     * @returns java.util.List<com.leansoft.fpml.nano.Reason>
	 */
	public List<Reason> getReason() {
	    return this.reason;
	}
	
	/**
	 * public setter
	 *
     * @param java.util.List<com.leansoft.fpml.nano.Reason>
	 */
	public void setReason(List<Reason> reason) {
	    this.reason = reason;
	}

}