// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

/**
 * The ISDA defined methodology for determining the final price of the reference obligation for purposes of cash settlement.
 */
public enum ValuationMethodEnum {

    MARKET("Market"),
  

    HIGHEST("Highest"),
  

    AVERAGE_MARKET("AverageMarket"),
  

    AVERAGE_HIGHEST("AverageHighest"),
  

    BLENDED_MARKET("BlendedMarket"),
  

    BLENDED_HIGHEST("BlendedHighest"),
  

    AVERAGE_BLENDED_MARKET("AverageBlendedMarket"),
  

    AVERAGE_BLENDED_HIGHEST("AverageBlendedHighest");
  
  
    private final String value;
  
    ValuationMethodEnum(String v) {
        value = v;
    }
    
    public String value() {
        return value;
    }
    
    public static ValuationMethodEnum fromValue(String v) {
        if (v != null) {
            for (ValuationMethodEnum c: ValuationMethodEnum.values()) {
                if (c.value.equals(v)) {
                    return c;
                }
            }
        }
        throw new IllegalArgumentException(v);
    }
}