// Generated by xsd compiler for android/java
// DO NOT CHANGE!
package com.leansoft.fpml.nano;

import java.io.Serializable;
import com.leansoft.nano.annotation.*;

/**
 * Calculation of a Variance Amount.
 */
public class VarianceAmount extends CalculatedAmount implements Serializable {

    private static final long serialVersionUID = -1L;

	@Element
	private Variance variance;
	
    
	/**
     * public getter
     *
     * Specifies Variance.
     *
     * @returns com.leansoft.fpml.nano.Variance
	 */
	public Variance getVariance() {
	    return this.variance;
	}
	
	/**
	 * public setter
	 *
     * Specifies Variance.
     *
     * @param com.leansoft.fpml.nano.Variance
	 */
	public void setVariance(Variance variance) {
	    this.variance = variance;
	}

}